const fs = require('fs');
const path = require('path');
if (fs.existsSync(path.join(__dirname, 'node_modules', 'dotenv'))) require('dotenv').config();
else if (fs.existsSync(path.join(__dirname, '.env'))) require('./scripts/env').loadEnv();
const express = require('express');
const { google } = require('googleapis');
const Database = require('better-sqlite3');
const { randomUUID, randomBytes, scryptSync, timingSafeEqual, createHmac } = require('crypto');
const nanoid = () => randomUUID().replace(/-/g, '').slice(0, 21);
const APP_VERSION = process.env.APP_VERSION || readCommit() || 'dev';
const DB_PATH = process.env.DATABASE_PATH || './data/campstore.sqlite';
const SESSION_SECRET = process.env.SESSION_SECRET || process.env.DEFAULT_OWNER_PASSWORD || 'campstore-dev-session-secret';
const ROLES = { OWNER: 3, ADMIN: 2, CLERK: 1 };
fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });
const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');
migrate();
const INITIAL_SEED_RESULT = seedDefaultOwner();
const app = express();
app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: false }));
function readCommit(){try{return require('child_process').execSync('git rev-parse --short HEAD',{stdio:['ignore','pipe','ignore']}).toString().trim()}catch{return null}}
function migrate(){
 db.exec(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS items(id TEXT PRIMARY KEY,name TEXT NOT NULL,cost_cents INTEGER NOT NULL,category TEXT NOT NULL DEFAULT 'Uncategorized',active INTEGER NOT NULL DEFAULT 1,sku TEXT,notes TEXT,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS campers(id TEXT PRIMARY KEY,name TEXT NOT NULL,person_type TEXT NOT NULL DEFAULT 'Camper',initial_balance_cents INTEGER NOT NULL,current_balance_cents INTEGER NOT NULL,sheet_row INTEGER,active INTEGER NOT NULL DEFAULT 1,notes TEXT,source TEXT NOT NULL DEFAULT 'google',updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,clerk TEXT,camper_id TEXT NOT NULL,camper_name TEXT NOT NULL,previous_balance_cents INTEGER NOT NULL,total_cents INTEGER NOT NULL,new_balance_cents INTEGER NOT NULL,items_json TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',synced_at TEXT,error TEXT,FOREIGN KEY(camper_id) REFERENCES campers(id));
 CREATE TABLE IF NOT EXISTS sync_events(id INTEGER PRIMARY KEY AUTOINCREMENT,created_at TEXT NOT NULL,type TEXT NOT NULL,status TEXT NOT NULL,message TEXT);
 CREATE TABLE IF NOT EXISTS balance_adjustments(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,admin TEXT,camper_id TEXT NOT NULL,camper_name TEXT NOT NULL,action TEXT NOT NULL,amount_cents INTEGER,previous_balance_cents INTEGER NOT NULL,new_balance_cents INTEGER NOT NULL,reason TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',synced_at TEXT,error TEXT);
 CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,admin TEXT,action TEXT NOT NULL,person_id TEXT,person_name TEXT,initial_balance_cents INTEGER,current_balance_cents INTEGER,details_json TEXT);
 CREATE TABLE IF NOT EXISTS account_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,camper_id TEXT NOT NULL,entry_type TEXT NOT NULL,amount_cents INTEGER NOT NULL,balance_before_cents INTEGER NOT NULL,balance_after_cents INTEGER NOT NULL,payment_method TEXT,reason TEXT,transaction_id TEXT,balance_adjustment_id TEXT,audit_log_id TEXT,created_by_user_id TEXT,created_by_name TEXT,created_at TEXT NOT NULL,metadata_json TEXT,FOREIGN KEY(camper_id) REFERENCES campers(id),FOREIGN KEY(transaction_id) REFERENCES transactions(id),FOREIGN KEY(balance_adjustment_id) REFERENCES balance_adjustments(id),FOREIGN KEY(audit_log_id) REFERENCES audit_logs(id),FOREIGN KEY(created_by_user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('OWNER','ADMIN','CLERK')),password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);`);

 // Existing databases may have older tables. Add columns before any SQL below
 // references them (especially items.category in the category index/status queries).
 ensureColumn('items','category',"TEXT NOT NULL DEFAULT 'Uncategorized'");
 ensureColumn('items','active',"INTEGER NOT NULL DEFAULT 1");
 ensureColumn('items','sku',"TEXT");
 ensureColumn('items','notes',"TEXT");
 ensureColumn('campers','person_type',"TEXT NOT NULL DEFAULT 'Camper'");
 ensureColumn('campers','active',"INTEGER NOT NULL DEFAULT 1");
 ensureColumn('campers','notes',"TEXT");
 ensureColumn('campers','source',"TEXT NOT NULL DEFAULT 'google'");
 ensureColumn('campers','cabin',"TEXT");
 ensureColumn('campers','external_id',"TEXT");
 ensureColumn('items','stock_qty',"INTEGER");
 ensureColumn('users','active',"INTEGER NOT NULL DEFAULT 1");
 db.exec(`CREATE TABLE IF NOT EXISTS user_page_permissions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,permission_key TEXT NOT NULL,allowed INTEGER NOT NULL CHECK(allowed IN (0,1)),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,UNIQUE(user_id,permission_key));
 CREATE INDEX IF NOT EXISTS idx_user_page_permissions_user ON user_page_permissions(user_id);
 CREATE INDEX IF NOT EXISTS idx_user_page_permissions_key ON user_page_permissions(permission_key);
 CREATE TABLE IF NOT EXISTS stock_adjustments(id TEXT PRIMARY KEY,item_id TEXT NOT NULL,quantity_change INTEGER NOT NULL CHECK(quantity_change > 0),resulting_quantity INTEGER NOT NULL,adjustment_type TEXT NOT NULL,reason TEXT,user_id TEXT,created_at TEXT NOT NULL,FOREIGN KEY(item_id) REFERENCES items(id),FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE INDEX IF NOT EXISTS idx_stock_adjustments_item ON stock_adjustments(item_id);
 CREATE INDEX IF NOT EXISTS idx_stock_adjustments_user ON stock_adjustments(user_id);`);

 db.exec(`CREATE INDEX IF NOT EXISTS idx_campers_name ON campers(name);
 CREATE INDEX IF NOT EXISTS idx_campers_cabin ON campers(cabin);
 CREATE INDEX IF NOT EXISTS idx_campers_external ON campers(external_id);
 CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
 CREATE INDEX IF NOT EXISTS idx_account_ledger_camper ON account_ledger(camper_id);
 CREATE INDEX IF NOT EXISTS idx_account_ledger_created ON account_ledger(created_at);
 CREATE INDEX IF NOT EXISTS idx_account_ledger_transaction ON account_ledger(transaction_id);
 CREATE INDEX IF NOT EXISTS idx_account_ledger_adjustment ON account_ledger(balance_adjustment_id);`);
 backfillAccountLedger();
 ensureItemsNameCategoryIndex();
 setDefault('allow_over_balance', String(process.env.ALLOW_OVER_BALANCE === 'true'));
}
function tableColumns(table){return db.prepare(`PRAGMA table_info(${table})`).all().map(c=>c.name)}
function ensureColumn(table,column,definition){const cols=tableColumns(table); if(!cols.includes(column)){db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`); console.log(`[migration] Added ${table}.${column}`)} else console.log(`[migration] ${table}.${column} already exists`)}
function ensureItemsNameCategoryIndex(){const duplicates=db.prepare('SELECT lower(name) name_key, lower(category) category_key, count(*) c FROM items GROUP BY lower(name), lower(category) HAVING c > 1 LIMIT 1').get(); if(duplicates){console.log('[migration] Skipped idx_items_name_category because duplicate item names/categories already exist'); return} db.exec('CREATE UNIQUE INDEX IF NOT EXISTS idx_items_name_category ON items(lower(name),lower(category))'); console.log('[migration] Ensured idx_items_name_category')}
function setDefault(k,v){db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v)}
function jsonOrNull(value){return value==null?null:(typeof value==='string'?value:JSON.stringify(value))}
function insertAccountLedger(conn,entry){const info=conn.prepare('INSERT INTO account_ledger(camper_id,entry_type,amount_cents,balance_before_cents,balance_after_cents,payment_method,reason,transaction_id,balance_adjustment_id,audit_log_id,created_by_user_id,created_by_name,created_at,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(entry.camper_id,entry.entry_type,entry.amount_cents,entry.balance_before_cents,entry.balance_after_cents,entry.payment_method||null,entry.reason||null,entry.transaction_id||null,entry.balance_adjustment_id||null,entry.audit_log_id||null,entry.created_by_user_id||null,entry.created_by_name||null,entry.created_at||now(),jsonOrNull(entry.metadata_json)); return conn.prepare('SELECT * FROM account_ledger WHERE id=?').get(info.lastInsertRowid)}
function recordOpeningLedger(conn,{camperId,balanceCents,auditLogId,user,createdAt,metadata}){if(!balanceCents) return null; return insertAccountLedger(conn,{camper_id:camperId,entry_type:'opening_balance',amount_cents:balanceCents,balance_before_cents:0,balance_after_cents:balanceCents,audit_log_id:auditLogId,created_by_user_id:user?.id||null,created_by_name:user?.displayName||user?.display_name||null,created_at:createdAt,metadata_json:{zero_entry_policy:'omit_zero_opening_balance',...(metadata||{})}})}
function applyBalanceChange(conn,{camperId,entryType,deltaCents,setBalanceCents,paymentMethod,reason,transactionId,balanceAdjustmentId,auditLogId,user,createdAt,metadata}){const camper=conn.prepare('SELECT * FROM campers WHERE id=?').get(camperId); if(!camper) throw Error('Camper not found'); const before=camper.current_balance_cents; const after=setBalanceCents!==undefined&&setBalanceCents!==null?setBalanceCents:before+deltaCents; const amount=after-before; if(entryType==='purchase'&&amount>=0) throw Error('Purchase ledger amount must be negative'); if(entryType==='funds_added'&&amount<=0) throw Error('Funds-added ledger amount must be positive'); conn.prepare('UPDATE campers SET current_balance_cents=?,updated_at=? WHERE id=?').run(after,createdAt||now(),camperId); const ledger=insertAccountLedger(conn,{camper_id:camperId,entry_type:entryType,amount_cents:amount,balance_before_cents:before,balance_after_cents:after,payment_method:paymentMethod,reason,transaction_id:transactionId,balance_adjustment_id:balanceAdjustmentId,audit_log_id:auditLogId,created_by_user_id:user?.id||null,created_by_name:user?.displayName||user?.display_name||null,created_at:createdAt,metadata_json:metadata}); return {camper:conn.prepare('SELECT * FROM campers WHERE id=?').get(camperId),ledger}}
function backfillAccountLedger(){
 db.prepare("INSERT INTO account_ledger(camper_id,entry_type,amount_cents,balance_before_cents,balance_after_cents,transaction_id,created_by_name,created_at,metadata_json) SELECT t.camper_id,'purchase',t.new_balance_cents-t.previous_balance_cents,t.previous_balance_cents,t.new_balance_cents,t.id,t.clerk,t.created_at,json_object('backfilled',1,'source','transactions') FROM transactions t WHERE NOT EXISTS (SELECT 1 FROM account_ledger l WHERE l.transaction_id=t.id)").run();
 db.prepare("INSERT INTO account_ledger(camper_id,entry_type,amount_cents,balance_before_cents,balance_after_cents,balance_adjustment_id,created_by_name,reason,created_at,metadata_json) SELECT a.camper_id,CASE WHEN a.action='add' THEN 'funds_added' WHEN a.action='subtract' THEN 'funds_subtracted' WHEN a.action='set' THEN 'balance_set' WHEN a.action LIKE 'reconcile_%' THEN 'reconciliation' ELSE 'manual_adjustment' END,a.new_balance_cents-a.previous_balance_cents,a.previous_balance_cents,a.new_balance_cents,a.id,a.admin,a.reason,a.created_at,json_object('backfilled',1,'source','balance_adjustments') FROM balance_adjustments a WHERE NOT EXISTS (SELECT 1 FROM account_ledger l WHERE l.balance_adjustment_id=a.id)").run();
}

function seedDefaultOwner(){const existingCount=db.prepare('SELECT count(*) c FROM users').get().c; if(existingCount>0) return {seeded:false,reason:'users-exist'}; const username=process.env.DEFAULT_OWNER_USERNAME, password=process.env.DEFAULT_OWNER_PASSWORD; if(!username||!password) return {seeded:false,reason:'missing-env'}; const display=process.env.DEFAULT_OWNER_DISPLAY_NAME||username; const stamp=now(); db.prepare('INSERT INTO users(id,username,display_name,role,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('user_'+nanoid(),username,display,'OWNER',hashPassword(password),1,stamp,stamp); return {seeded:true,username}}
function hashPassword(password){const salt=randomBytes(16).toString('hex'); const hash=scryptSync(password,salt,64).toString('hex'); return `scrypt$${salt}$${hash}`}
function verifyPassword(password,stored){const [scheme,salt,hash]=String(stored||'').split('$'); if(scheme!=='scrypt'||!salt||!hash) return false; const actual=Buffer.from(hash,'hex'); const check=scryptSync(password,salt,64); return actual.length===check.length && timingSafeEqual(actual,check)}
function sign(value){return createHmac('sha256',SESSION_SECRET).update(value).digest('base64url')}
function makeSession(user){const payload=Buffer.from(JSON.stringify({id:user.id,username:user.username,displayName:user.display_name,role:user.role,exp:Date.now()+1000*60*60*12})).toString('base64url'); return `${payload}.${sign(payload)}`}
function parseCookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').filter(Boolean).map(p=>{const i=p.indexOf('='); return [p.slice(0,i).trim(),decodeURIComponent(p.slice(i+1))]}))}
function currentUser(req){const token=parseCookies(req).campstore_session; if(!token) return null; const [payload,sig]=token.split('.'); if(!payload||sig!==sign(payload)) return null; try{const data=JSON.parse(Buffer.from(payload,'base64url').toString()); if(data.exp<Date.now()) return null; const user=db.prepare('SELECT id,username,display_name,role,active FROM users WHERE id=? AND active=1').get(data.id); return user?{id:user.id,username:user.username,displayName:user.display_name,role:user.role}:null}catch{return null}}

const PAGE_REGISTRY = [
 {key:'page.clerk',slug:'clerk',label:'Clerk',route:'/clerk',file:'index.html'},
 {key:'page.stock',slug:'stock',label:'Stock',route:'/stock',file:'stock.html'},
 {key:'page.people',slug:'people',label:'People',route:'/people',file:'admin.html'},
 {key:'page.items',slug:'items',label:'Items',route:'/items',file:'admin.html'},
 {key:'page.transactions',slug:'transactions',label:'Transactions',route:'/transactions',file:'admin.html'},
 {key:'page.sync',slug:'sync',label:'Sync',route:'/sync',file:'admin.html'},
 {key:'page.users',slug:'users',label:'Users',route:'/users',file:'admin.html'},
 {key:'page.settings',slug:'settings',label:'Settings',route:'/settings',file:'admin.html'},
 {key:'page.admin',slug:'admin',label:'Admin',route:'/admin',file:'admin.html'}
];
const PAGE_KEYS = new Set(PAGE_REGISTRY.map(p=>p.key));
const ROLE_DEFAULTS = {OWNER:PAGE_REGISTRY.map(p=>p.key),ADMIN:PAGE_REGISTRY.map(p=>p.key),CLERK:['page.clerk']};
function permissionOverrides(userId){return Object.fromEntries(db.prepare('SELECT permission_key,allowed FROM user_page_permissions WHERE user_id=?').all(userId).map(r=>[r.permission_key,!!r.allowed]))}
function getEffectivePermissions(user){const keys={}; for(const p of PAGE_REGISTRY){let allowed=user.role==='OWNER'||(ROLE_DEFAULTS[user.role]||[]).includes(p.key); const ov=permissionOverrides(user.id)[p.key]; if(user.role!=='OWNER'&&ov!==undefined) allowed=ov; keys[p.key]=allowed} return keys}
function userHasPermission(user,key){if(!user||!PAGE_KEYS.has(key)) return false; if(user.role==='OWNER') return true; const ov=db.prepare('SELECT allowed FROM user_page_permissions WHERE user_id=? AND permission_key=?').get(user.id,key); if(ov) return !!ov.allowed; return (ROLE_DEFAULTS[user.role]||[]).includes(key)}
function allowedPages(user){const eff=getEffectivePermissions(user); return PAGE_REGISTRY.filter(p=>eff[p.key])}
function requirePermission(key){return (req,res,next)=>{if(!req.user) return requireAuth(req,res,()=>requirePermission(key)(req,res,next)); if(!userHasPermission(req.user,key)) return wantsHtml(req)?res.status(403).sendFile(path.join(__dirname,'public','403.html')):res.status(403).json({error:'Forbidden'}); next()}}
function requireAnyPermission(keys){return (req,res,next)=>{if(!req.user) return requireAuth(req,res,()=>requireAnyPermission(keys)(req,res,next)); if(!keys.some(k=>userHasPermission(req.user,k))) return res.status(403).json({error:'Forbidden'}); next()}}
function isFinalActiveOwner(id){const u=db.prepare('SELECT role,active FROM users WHERE id=?').get(id); return u&&u.role==='OWNER'&&u.active===1&&db.prepare("SELECT count(*) c FROM users WHERE role='OWNER' AND active=1").get().c<=1}

function requireAuth(req,res,next){const user=currentUser(req); if(!user) return wantsHtml(req)?res.redirect('/login.html'):res.status(401).json({error:'Authentication required'}); req.user=user; next()}
function requireRole(...roles){return (req,res,next)=>{if(!req.user) return requireAuth(req,res,()=>requireRole(...roles)(req,res,next)); const min=Math.min(...roles.map(r=>ROLES[r])); if(ROLES[req.user.role]<min) return wantsHtml(req)?res.status(403).send('Forbidden'):res.status(403).json({error:'Forbidden'}); next()}}
function wantsHtml(req){return (req.headers.accept||'').includes('text/html') || !(req.originalUrl||req.path).startsWith('/api/')}
function cents(v){ if (typeof v === 'number') return Math.round(v*100); const s=String(v||'').replace(/[$,]/g,'').trim(); if(!s) throw Error('missing money value'); const n=Number(s); if(Number.isNaN(n)) throw Error('invalid money value '+v); return Math.round(n*100)}
function money(c){return (c/100).toFixed(2)}
function now(){return new Date().toISOString()}

function getSetting(key){return db.prepare('SELECT value FROM settings WHERE key=?').get(key)?.value||''}
function saveSetting(key,value){db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,String(value||''))}
const DEFAULT_SHEETS = { campers: 'Campers / Balances', logs: 'Logs' };
function extractSpreadsheetId(input){
 const value=String(input||'').trim();
 if(!value) return '';
 const match=value.match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);
 if(match) return match[1];
 return value;
}
function quoteSheetName(name){return `'${String(name).replace(/'/g,"''")}'`}
function googleConfig(){
 const sheetUrl=getSetting('google_sheet_url')||process.env.GOOGLE_SHEET_URL||'';
 const savedId=getSetting('google_spreadsheet_id')||process.env.GOOGLE_SPREADSHEET_ID||'';
 const spreadsheetId=extractSpreadsheetId(savedId||sheetUrl);
 const sheetNames={
  campers:getSetting('google_campers_sheet_name')||process.env.GOOGLE_CAMPERS_SHEET_NAME||DEFAULT_SHEETS.campers,
  logs:getSetting('google_logs_sheet_name')||process.env.GOOGLE_LOGS_SHEET_NAME||DEFAULT_SHEETS.logs
 };
 const email=getSetting('google_service_account_email')||process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||'';
 const rawKey=getSetting('google_private_key')||process.env.GOOGLE_PRIVATE_KEY||'';
 const privateKey=rawKey.replace(/\\n/g,'\n');
 return {sheetUrl,spreadsheetId,sheetNames,email,privateKey,source:getSetting('google_spreadsheet_id')?'database':'env'};
}
function googleStatus(){const c=googleConfig(); const pendingTransactions=db.prepare("SELECT count(*) c FROM transactions WHERE sync_status!='synced'").get().c; const pendingAdjustments=db.prepare("SELECT count(*) c FROM balance_adjustments WHERE sync_status!='synced'").get().c; return {configured:!!(c.spreadsheetId&&c.email&&c.privateKey),sheetUrl:c.sheetUrl||'',spreadsheetId:c.spreadsheetId?`configured · ${String(c.spreadsheetId).slice(-4)}`:'missing',spreadsheetIdValue:c.spreadsheetId||'',sheetNames:c.sheetNames,serviceAccountEmail:c.email||'',privateKey:c.privateKey?`configured · ${String(c.privateKey).replace(/\n/g,'').slice(-4)}`:'missing',source:c.source,lastImport:getSetting('last_import')||null,lastSync:getSetting('last_sync')||null,pending:pendingTransactions+pendingAdjustments,pendingGoogleSync:pendingTransactions+pendingAdjustments,pendingTransactions,pendingAdjustments}}
function sheetsClient(){ const c=googleConfig(); if(!c.spreadsheetId) throw Error('Missing spreadsheet ID or Google Sheet URL'); if(!c.email) throw Error('Missing service account email'); if(!c.privateKey) throw Error('Missing private key'); const auth = new google.auth.JWT(c.email, null, c.privateKey, ['https://www.googleapis.com/auth/spreadsheets']); return {sheets:google.sheets({version:'v4', auth}), spreadsheetId:c.spreadsheetId,sheetNames:c.sheetNames};}
async function validateSheetTabs(sheets,spreadsheetId,required){const meta=await sheets.spreadsheets.get({spreadsheetId,fields:'sheets.properties.title'}); const tabs=new Set((meta.data.sheets||[]).map(s=>s.properties.title)); const needed=required||[googleConfig().sheetNames.campers,googleConfig().sheetNames.logs]; const missing=needed.filter(t=>!tabs.has(t)); if(missing.length) throw Error('Invalid tab names. Missing required tab(s): '+missing.join(', ')); return [...tabs]}
async function verifyEditAccess(sheets,spreadsheetId,sheetName){const range=`${quoteSheetName(sheetName)}!A1`; const current=await sheets.spreadsheets.values.get({spreadsheetId,range}); const value=current.data.values?.[0]?.[0]||''; await sheets.spreadsheets.values.update({spreadsheetId,range,valueInputOption:'USER_ENTERED',requestBody:{values:[[value]]}})}
function parseMoneyCell(value,label){try{return cents(value)}catch(e){throw Error(`${label}: ${e.message}`)}}
function parseCsv(text){
 const rows=[]; let row=[], cell='', inQuotes=false; const data=String(text||'').replace(/^\ufeff/,'');
 for(let i=0;i<data.length;i++){const ch=data[i], next=data[i+1]; if(inQuotes){if(ch==='"'&&next==='"'){cell+='"'; i++} else if(ch==='"') inQuotes=false; else cell+=ch} else if(ch==='"') inQuotes=true; else if(ch===','){row.push(cell); cell=''} else if(ch==='\n'){row.push(cell); rows.push(row); row=[]; cell=''} else if(ch==='\r'){} else cell+=ch}
 row.push(cell); if(row.some(v=>String(v).trim()!=='')) rows.push(row); return rows;
}
function itemCsvTemplate(){return 'Cost,Item Name,Category,Active,SKU,Notes\n1.50,Snack,Food,true,SNACK-001,Example item\n'}
function validateItemsCsv(text){
 const rows=parseCsv(text); if(!rows.length) return {headers:[],validRows:[],errors:['CSV is empty'],skipped:0};
 const headers=rows[0].map(h=>String(h).trim()); const idx=Object.fromEntries(headers.map((h,i)=>[h.toLowerCase(),i]));
 const req=['cost','item name','category'], errors=[], validRows=[], seen=new Set(); let skipped=0;
 for(const h of req) if(idx[h]===undefined) errors.push(`Missing required column: ${h==='cost'?'Cost':h==='item name'?'Item Name':'Category'}`);
 if(errors.length) return {headers,validRows,errors,skipped};
 for(const [n,row] of rows.slice(1).entries()){const rowNum=n+2; if(row.every(c=>String(c||'').trim()==='')){skipped++; continue}
  const name=String(row[idx['item name']]||'').trim(), category=String(row[idx.category]||'').trim(), rawCost=String(row[idx.cost]||'').trim();
  if(!rawCost) errors.push(`Row ${rowNum}: missing Cost`); let cost=null; if(rawCost) try{cost=cents(rawCost)}catch{errors.push(`Row ${rowNum}: invalid Cost`)}
  if(!name) errors.push(`Row ${rowNum}: missing Item Name`); if(!category) errors.push(`Row ${rowNum}: missing Category`);
  const key=`${name.toLowerCase()}|${category.toLowerCase()}`; if(name&&category&&seen.has(key)) errors.push(`Row ${rowNum}: duplicate item name in same category (${name} / ${category})`); seen.add(key);
  if(name&&category&&cost!==null) validRows.push({name,category,cost_cents:cost,active:parseBool(row[idx.active],true),sku:String(row[idx.sku]||'').trim(),notes:String(row[idx.notes]||'').trim()});
 }
 return {headers,validRows,errors,skipped};
}
function validatePersonType(value){const type=String(value||'Camper').trim(); return ['Camper','Staff','Other'].includes(type)?type:'Other'}
function parseBool(v,def=true){const s=String(v??'').trim().toLowerCase(); if(!s) return def; return ['1','true','yes','y','active','enabled'].includes(s)?1:0}
function parseStock(v){if(v===undefined||v===null||String(v).trim()==='') return null; const n=Math.round(Number(v)); if(Number.isNaN(n)) throw Error('invalid stock quantity'); return n}
function applyItemsImport(validRows,disableMissing){const stamp=now(); const keep=[]; const run=db.transaction(()=>{for(const item of validRows){const existing=db.prepare('SELECT id FROM items WHERE lower(name)=lower(?) AND lower(category)=lower(?)').get(item.name,item.category); const id=existing?.id||'item_'+nanoid(); keep.push(id); db.prepare('INSERT INTO items(id,name,cost_cents,category,active,sku,notes,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,cost_cents=excluded.cost_cents,category=excluded.category,active=excluded.active,sku=excluded.sku,notes=excluded.notes,updated_at=excluded.updated_at').run(id,item.name,item.cost_cents,item.category,item.active,item.sku,item.notes,stamp)} if(disableMissing&&keep.length) db.prepare(`UPDATE items SET active=0,updated_at=? WHERE id NOT IN (${keep.map(()=>'?').join(',')})`).run(stamp,...keep)}); run(); event('import_items_csv','ok',`Imported ${validRows.length} CSV items${disableMissing?'; disabled missing items':''}`); return {ok:true,imported:validRows.length,disabledMissing:!!disableMissing,lastImport:stamp}}
// --- Roster / reconciliation import (UltraCamp exports + generic CSV) ---
function rosterTemplate(){return 'Cabin,Child Name,Balance\nWhippoorwill,Aubree Bailes,25.00\nCoyote,Bryce Allred,45.00\nRaccoon,Julian Allen,15.00\n'}
function normHeader(h){return String(h||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function parseRosterCsv(text){
 const rows=parseCsv(text);
 if(!rows.length) return {format:null,detected:'empty',people:[],errors:['CSV is empty'],skipped:0};
 const headers=rows[0].map(h=>String(h).trim());
 const idx={}; headers.forEach((h,i)=>{const k=normHeader(h); if(idx[k]===undefined) idx[k]=i});
 const has=k=>idx[k]!==undefined;
 const hasFacility=has('facilityname'), hasFirst=has('namefirst'), hasLast=has('namelast'), hasAmount=has('amount'), hasPerson=has('idperson');
 let format,detected,nameCol,cabinCol,balCol;
 if(hasAmount&&(hasFirst||hasLast)){format='ultracamp_deposits'; detected='UltraCamp Store Deposits'}
 else if(hasFacility&&(hasFirst||hasLast)){format='ultracamp_cabins'; detected='UltraCamp Cabin Assignments'}
 else{
  const nameKey=['childname','name','camper','fullname','student'].find(has);
  if(!nameKey&&!(hasFirst||hasLast)) return {format:null,detected:'unknown',people:[],errors:['Could not find a name column. Use a "Child Name" column, or an UltraCamp export with nameFirst/nameLast.'],skipped:0,headers};
  format='generic'; detected='Generic roster CSV';
  nameCol=nameKey!==undefined?idx[nameKey]:undefined;
  const cabinKey=['cabin','facilityname','facility','lodging','group','unit'].find(has); cabinCol=cabinKey!==undefined?idx[cabinKey]:undefined;
  const balKey=['balance','currentbalance','amount','deposit','initialbalance','funds'].find(has); balCol=balKey!==undefined?idx[balKey]:undefined;
 }
 const nameOf=row=>{ if(format==='generic'&&nameCol!==undefined) return String(row[nameCol]||'').trim(); const f=hasFirst?String(row[idx.namefirst]||'').trim():''; const l=hasLast?String(row[idx.namelast]||'').trim():''; return `${f} ${l}`.trim() };
 const cabinOf=row=>format==='generic'?(cabinCol!==undefined?String(row[cabinCol]||'').trim():''):(hasFacility?String(row[idx.facilityname]||'').trim():'');
 const map=new Map(); const errors=[]; let skipped=0;
 for(const [n,row] of rows.slice(1).entries()){
  const rowNum=n+2; if(row.every(c=>String(c||'').trim()==='')){skipped++; continue}
  const name=nameOf(row); if(!name){skipped++; continue}
  const extId=hasPerson?String(row[idx.idperson]||'').trim():'';
  const cabin=cabinOf(row);
  const key=extId?'id:'+extId:'name:'+name.toLowerCase();
  let rec=map.get(key); if(!rec){rec={external_id:extId,name,cabin:'',depositTotal:0,balance:null,hasBalance:false,rows:0}; map.set(key,rec)}
  if(cabin) rec.cabin=cabin; rec.rows++;
  if(format==='ultracamp_deposits'){const raw=String(row[idx.amount]||'').trim(); if(raw){try{rec.depositTotal+=cents(raw); rec.hasBalance=true}catch{errors.push(`Row ${rowNum}: invalid amount "${raw}"`)}}}
  else if(format==='generic'&&balCol!==undefined){const raw=String(row[balCol]||'').trim(); if(raw){try{rec.balance=cents(raw); rec.hasBalance=true}catch{errors.push(`Row ${rowNum}: invalid balance "${raw}"`)}}}
 }
 const people=[...map.values()].map(r=>({external_id:r.external_id||null,name:r.name,cabin:r.cabin||null,hasBalance:r.hasBalance,balance:format==='ultracamp_deposits'?r.depositTotal:r.balance,depositTotal:r.depositTotal,rows:r.rows}));
 return {format,detected,people,errors,skipped,carriesBalance:people.some(p=>p.hasBalance),carriesCabin:people.some(p=>p.cabin)};
}
function findCamperForRoster(p){ if(p.external_id){const byId=db.prepare('SELECT * FROM campers WHERE external_id=?').get(p.external_id); if(byId) return byId} return db.prepare("SELECT * FROM campers WHERE lower(name)=lower(?) ORDER BY (external_id IS NULL), source='manual' DESC LIMIT 1").get(p.name) }
function reconcilePlan(parsed,opts){
 const isDeposit=parsed.format==='ultracamp_deposits';
 const items=[]; const summary={newPeople:0,skippedNew:0,cabinChanges:0,balanceChanges:0,unchanged:0,totalBalanceDelta:0};
 for(const p of parsed.people){
  const existing=findCamperForRoster(p);
  const entry={name:p.name,cabin:p.cabin,external_id:p.external_id,existingId:existing?.id||null};
  if(!existing){ if(!opts.createNew){summary.skippedNew++; continue} entry.type='new'; entry.newBalance=p.hasBalance?p.balance:0; summary.newPeople++; summary.totalBalanceDelta+=entry.newBalance; items.push(entry); continue}
  entry.currentCabin=existing.cabin||null; entry.currentBalance=existing.current_balance_cents;
  let changed=false;
  if(opts.updateCabins&&p.cabin&&(existing.cabin||'')!==p.cabin){entry.cabinChange={from:existing.cabin||null,to:p.cabin}; summary.cabinChanges++; changed=true}
  if(opts.reconcileBalances&&p.hasBalance){
   if(isDeposit){const delta=p.balance-existing.initial_balance_cents; if(delta!==0){entry.balanceChange={mode:'deposit',delta,fromInitial:existing.initial_balance_cents,toInitial:p.balance,fromCurrent:existing.current_balance_cents,toCurrent:existing.current_balance_cents+delta}; summary.balanceChanges++; summary.totalBalanceDelta+=delta; changed=true}}
   else if(p.balance!==existing.current_balance_cents){const delta=p.balance-existing.current_balance_cents; entry.balanceChange={mode:'set',delta,fromCurrent:existing.current_balance_cents,toCurrent:p.balance}; summary.balanceChanges++; summary.totalBalanceDelta+=delta; changed=true}
  }
  entry.type=changed?'update':'unchanged'; if(!changed) summary.unchanged++; items.push(entry);
 }
 return {format:parsed.format,detected:parsed.detected,isDeposit,carriesBalance:parsed.carriesBalance,carriesCabin:parsed.carriesCabin,items,summary,errors:parsed.errors,skipped:parsed.skipped};
}
function applyRoster(parsed,opts,user){
 const plan=reconcilePlan(parsed,opts); const stamp=now(); let created=0,cabinsUpdated=0,balancesReconciled=0;
 const run=db.transaction(()=>{
  for(const e of plan.items){
   if(e.type==='new'){ if(!opts.createNew) continue; const id='roster_'+nanoid(); const bal=e.newBalance||0;
    db.prepare('INSERT INTO campers(id,name,person_type,initial_balance_cents,current_balance_cents,sheet_row,active,notes,source,cabin,external_id,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,e.name,'Camper',bal,bal,null,1,'',parsed.format==='generic'?'roster':'ultracamp',e.cabin||null,e.external_id||null,stamp);
    const auditId='audit_'+nanoid(); db.prepare('INSERT INTO audit_logs(id,created_at,admin,action,person_id,person_name,initial_balance_cents,current_balance_cents,details_json) VALUES(?,?,?,?,?,?,?,?,?)').run(auditId,stamp,user.displayName,'roster_person_create',id,e.name,bal,bal,JSON.stringify({cabin:e.cabin||null,external_id:e.external_id||null,source:parsed.detected})); recordOpeningLedger(db,{camperId:id,balanceCents:bal,auditLogId:auditId,user,createdAt:stamp,metadata:{source:'roster_import',import_source:parsed.detected}}); created++; continue }
   if(e.type!=='update') continue;
   if(e.external_id) db.prepare('UPDATE campers SET external_id=COALESCE(external_id,?) WHERE id=?').run(e.external_id,e.existingId);
   if(e.cabinChange){db.prepare('UPDATE campers SET cabin=?,updated_at=? WHERE id=?').run(e.cabinChange.to,stamp,e.existingId); cabinsUpdated++}
   if(e.balanceChange){const bc=e.balanceChange;
    if(bc.mode==='deposit') db.prepare('UPDATE campers SET initial_balance_cents=?,updated_at=? WHERE id=?').run(bc.toInitial,stamp,e.existingId);
    const adjId='adj_'+nanoid(); db.prepare('INSERT INTO balance_adjustments(id,created_at,admin,camper_id,camper_name,action,amount_cents,previous_balance_cents,new_balance_cents,reason) VALUES(?,?,?,?,?,?,?,?,?,?)').run(adjId,stamp,user.displayName,e.existingId,e.name,bc.mode==='deposit'?'reconcile_deposit':'reconcile_set',bc.delta,bc.fromCurrent,bc.toCurrent,`Reconciliation import (${parsed.detected})`); applyBalanceChange(db,{camperId:e.existingId,entryType:'reconciliation',setBalanceCents:bc.toCurrent,balanceAdjustmentId:adjId,reason:`Reconciliation import (${parsed.detected})`,user,createdAt:stamp,metadata:{source:'roster_import',import_source:parsed.detected,mode:bc.mode}}); balancesReconciled++ }
  }
 }); run();
 saveSetting('last_reconcile',stamp);
 event('roster_import','ok',`Reconciliation (${parsed.detected}): ${created} new, ${cabinsUpdated} cabin updates, ${balancesReconciled} balance adjustments`);
 return {ok:true,created,cabinsUpdated,balancesReconciled,summary:plan.summary,detected:parsed.detected,format:parsed.format,lastReconcile:stamp};
}
// --- CSV export ---
function csvCell(v){const s=String(v==null?'':v); return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function toCsv(headers,rows){return [headers.map(csvCell).join(','),...rows.map(r=>r.map(csvCell).join(','))].join('\r\n')+'\r\n'}
function sendCsv(res,filename,csv){res.type('text/csv').attachment(filename).send(csv)}

async function importCampers(){const {sheets,spreadsheetId,sheetNames}=sheetsClient(); await validateSheetTabs(sheets,spreadsheetId,[sheetNames.campers]); const r=await sheets.spreadsheets.values.get({spreadsheetId,range:`${quoteSheetName(sheetNames.campers)}!A2:C`}); const rows=r.data.values||[], seen=new Set(), warnings=[]; const stamp=now(); let imported=0, skipped=0; const run=db.transaction(()=>{for(const [i,row] of rows.entries()){if(!row[0]&&!row[1]&&!row[2]){skipped++; continue} if(!row[0]) throw Error(`${sheetNames.campers} row ${i+2}: missing child name`); const name=String(row[0]).trim(); const key=name.toLowerCase(); if(seen.has(key)) throw Error('Duplicate camper name: '+name); seen.add(key); const initial=parseMoneyCell(row[1],`${sheetNames.campers} row ${i+2} initial balance`); const current=parseMoneyCell(row[2],`${sheetNames.campers} row ${i+2} current balance`); const existing=db.prepare("SELECT * FROM campers WHERE lower(name)=lower(?) ORDER BY source='manual' DESC LIMIT 1").get(name); const id=existing?.id||'camper_'+Buffer.from(key).toString('hex').slice(0,32); if(existing){db.prepare('UPDATE campers SET name=?,person_type=COALESCE(person_type,?),initial_balance_cents=?,sheet_row=?,active=1,source=?,updated_at=? WHERE id=?').run(name,'Camper',initial,i+2,'google',stamp,id); if(existing.current_balance_cents!==current) applyBalanceChange(db,{camperId:id,entryType:'import_adjustment',setBalanceCents:current,createdAt:stamp,metadata:{source:'google_import',sheet_row:i+2,previous_initial_balance_cents:existing.initial_balance_cents,new_initial_balance_cents:initial}})} else {db.prepare('INSERT INTO campers(id,name,person_type,initial_balance_cents,current_balance_cents,sheet_row,active,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,name,'Camper',initial,current,i+2,1,'google',stamp); recordOpeningLedger(db,{camperId:id,balanceCents:current,createdAt:stamp,metadata:{source:'google_import',sheet_row:i+2}})} imported++}}); run(); saveSetting('last_import',stamp); event('import_campers','ok',`Imported ${imported} campers; skipped ${skipped} blank rows`); return {ok:true,imported,skipped,warnings,lastImport:stamp}}
async function syncPending(){const {sheets,spreadsheetId,sheetNames}=sheetsClient(); await validateSheetTabs(sheets,spreadsheetId,[sheetNames.campers,sheetNames.logs]); const pending=db.prepare("SELECT * FROM transactions WHERE sync_status!='synced' ORDER BY created_at").all(); const adjustments=db.prepare("SELECT * FROM balance_adjustments WHERE sync_status!='synced' ORDER BY created_at").all(); for(const t of pending){await sheets.spreadsheets.values.append({spreadsheetId,range:`${quoteSheetName(sheetNames.logs)}!A:I`,valueInputOption:'USER_ENTERED',requestBody:{values:[[t.created_at,t.clerk,t.camper_name,money(t.previous_balance_cents),money(t.total_cents),money(t.new_balance_cents),JSON.parse(t.items_json).map(i=>`${i.qty}x ${i.name} @ $${money(i.price_cents)}`).join('; '),t.id,'sale']]}}); const camper=db.prepare('SELECT sheet_row FROM campers WHERE id=?').get(t.camper_id); if(camper?.sheet_row) await sheets.spreadsheets.values.update({spreadsheetId,range:`${quoteSheetName(sheetNames.campers)}!C${camper.sheet_row}`,valueInputOption:'USER_ENTERED',requestBody:{values:[[money(t.new_balance_cents)]]}}); db.prepare("UPDATE transactions SET sync_status='synced',synced_at=?,error=NULL WHERE id=?").run(now(),t.id)} for(const a of adjustments){await sheets.spreadsheets.values.append({spreadsheetId,range:`${quoteSheetName(sheetNames.logs)}!A:I`,valueInputOption:'USER_ENTERED',requestBody:{values:[[a.created_at,a.admin,a.camper_name,money(a.previous_balance_cents),a.amount_cents==null?'':money(a.amount_cents),money(a.new_balance_cents),`${a.action}: ${a.reason}`,a.id,'balance_adjustment']]}}); const camper=db.prepare('SELECT sheet_row FROM campers WHERE id=?').get(a.camper_id); if(camper?.sheet_row) await sheets.spreadsheets.values.update({spreadsheetId,range:`${quoteSheetName(sheetNames.campers)}!C${camper.sheet_row}`,valueInputOption:'USER_ENTERED',requestBody:{values:[[money(a.new_balance_cents)]]}}); db.prepare("UPDATE balance_adjustments SET sync_status='synced',synced_at=?,error=NULL WHERE id=?").run(now(),a.id)} const stamp=now(); saveSetting('last_sync',stamp); event('sync','ok',`Synced ${pending.length} transactions and ${adjustments.length} adjustments`); return {ok:true,synced:pending.length,adjustmentsSynced:adjustments.length,lastSync:stamp}}

function parseJsonSafe(text,fallback=null){try{return JSON.parse(text)}catch{return fallback}}
function normalizedEntryLabel(type){return ({purchase:'Purchase',funds_added:'Funds added',funds_subtracted:'Funds removed',balance_set:'Balance set',manual_adjustment:'Adjustment',reconciliation:'Reconciliation',opening_balance:'Opening balance',import_adjustment:'Import adjustment'})[type]||String(type||'Ledger entry').replace(/_/g,' ').replace(/^./,c=>c.toUpperCase())}
function normalizePurchaseItems(itemsJson){const parsed=parseJsonSafe(itemsJson, null); if(!Array.isArray(parsed)) return {items:[],available:false,error:'Purchase details unavailable'}; const items=[]; for(const raw of parsed){if(!raw||typeof raw!=='object') continue; const name=String(raw.name||raw.item_name||raw.title||'Item').trim()||'Item'; const quantity=Math.max(1,Math.round(Number(raw.qty??raw.quantity??1))||1); const unit=Number.isInteger(raw.unit_price_cents)?raw.unit_price_cents:Number.isInteger(raw.price_cents)?raw.price_cents:Number.isInteger(raw.cost_cents)?raw.cost_cents:null; const line=Number.isInteger(raw.line_total_cents)?raw.line_total_cents:(unit==null?null:unit*quantity); items.push({name,quantity,unit_price_cents:unit,line_total_cents:line}); } return {items,available:items.length>0,error:items.length?'':'Purchase details unavailable'} }
function buildHistoryEntry(row){const metadata=parseJsonSafe(row.metadata_json,null); const entry={id:row.id,entry_type:row.entry_type,amount_cents:row.amount_cents,balance_before_cents:row.balance_before_cents,balance_after_cents:row.balance_after_cents,payment_method:row.payment_method,reason:row.reason,created_at:row.created_at,created_by_name:row.created_by_name,transaction_id:row.transaction_id,balance_adjustment_id:row.balance_adjustment_id,metadata_json:row.metadata_json,metadata,display_label:normalizedEntryLabel(row.entry_type),source_label:metadata?.source?normalizedEntryLabel(metadata.source):normalizedEntryLabel(row.entry_type)}; if(row.tx_id&&row.tx_camper_id===row.camper_id){const norm=normalizePurchaseItems(row.tx_items_json); entry.purchase={items:norm.items,total_cents:row.tx_total_cents,details_available:norm.available}; if(!norm.available) entry.purchase.error=norm.error;} else if(row.transaction_id){entry.purchase={items:[],total_cents:null,details_available:false,error:'Purchase details unavailable'};} if(row.adj_id&&row.adj_camper_id===row.camper_id){entry.adjustment={action:row.adj_action,reason:row.adj_reason,administrator_name:row.adj_admin,amount_cents:row.adj_amount_cents,previous_balance_cents:row.adj_previous_balance_cents,new_balance_cents:row.adj_new_balance_cents};} else if(row.balance_adjustment_id){entry.adjustment={details_available:false,error:'Adjustment details unavailable'};} return entry}

function event(type,status,message){db.prepare('INSERT INTO sync_events(created_at,type,status,message) VALUES(?,?,?,?)').run(now(),type,status,message||'')}
app.get('/login.html',(req,res)=>res.sendFile(path.join(__dirname,'public','login.html')));
app.get('/login',(req,res)=>res.redirect('/login.html'));
app.post('/api/login',(req,res)=>{const {username,password}=req.body||{}; const user=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(String(username||'')); if(!user||!verifyPassword(String(password||''),user.password_hash)) return res.status(401).json({error:'Invalid username or password'}); res.cookie('campstore_session',makeSession(user),{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true',maxAge:1000*60*60*12}); const first=allowedPages({id:user.id,role:user.role})[0]?.route||'/access-denied'; res.json({ok:true,redirect:first,user:{username:user.username,displayName:user.display_name,role:user.role}})});
app.post('/api/logout',(req,res)=>{res.clearCookie('campstore_session'); res.json({ok:true})});
app.get('/api/me',requireAuth,(req,res)=>res.json({user:req.user,pages:PAGE_REGISTRY,permissions:getEffectivePermissions(req.user),allowedPages:allowedPages(req.user)}));
app.get('/',requireAuth,(req,res)=>{const first=allowedPages(req.user)[0]; return first?res.redirect(first.route):res.redirect('/access-denied')});
app.get('/access-denied',requireAuth,(req,res)=>res.sendFile(path.join(__dirname,'public','403.html')));
for(const page of PAGE_REGISTRY){app.get(page.route,requireAuth,requirePermission(page.key),(req,res)=>res.sendFile(path.join(__dirname,'public',page.file)))}
app.get('/people/:id/history',requireAuth,requirePermission('page.people'),(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
app.get('/index.html',requireAuth,requirePermission('page.clerk'),(req,res)=>res.redirect('/clerk'));
app.get('/admin.html',requireAuth,requireAnyPermission(['page.admin','page.people','page.items','page.transactions','page.sync','page.users','page.settings']),(req,res)=>res.redirect('/admin'));
app.use(express.static(path.join(__dirname, 'public'), { index: false }));
app.use('/api',requireAuth);
app.get('/api/state',(req,res)=>{res.json({user:req.user,allowedPages:allowedPages(req.user),permissions:getEffectivePermissions(req.user),items:db.prepare('SELECT * FROM items WHERE active=1 ORDER BY name').all(),campers:db.prepare('SELECT * FROM campers WHERE active=1 ORDER BY name').all(),settings:Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(r=>[r.key,r.value])),pending:db.prepare("SELECT count(*) c FROM transactions WHERE sync_status!='synced'").get().c,pendingGoogleSync:db.prepare("SELECT count(*) c FROM transactions WHERE sync_status!='synced'").get().c,version:APP_VERSION})});

app.get('/api/items',requirePermission('page.items'),(req,res)=>res.json(db.prepare('SELECT * FROM items ORDER BY category,name').all()));
app.post('/api/items',requirePermission('page.items'),(req,res)=>{try{const {name,cost,category,active,sku,notes,stock_qty}=req.body||{}; if(!String(name||'').trim()) throw Error('Item name is required'); if(!String(category||'').trim()) throw Error('Category is required'); const stamp=now(); db.prepare('INSERT INTO items(id,name,cost_cents,category,active,sku,notes,stock_qty,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run('item_'+nanoid(),String(name).trim(),cents(cost),String(category).trim(),active===false?0:1,String(sku||''),String(notes||''),parseStock(stock_qty),stamp); res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
function updateItemRoute(req,res){try{const body=req.body||{}; const {name,cost,category,active,sku,notes}=body; const item=db.prepare('SELECT * FROM items WHERE id=?').get(req.params.id); if(!item) return res.status(404).json({error:'Item not found'}); const nextStock='stock_qty' in body?parseStock(body.stock_qty):item.stock_qty; db.prepare('UPDATE items SET name=?,cost_cents=?,category=?,active=?,sku=?,notes=?,stock_qty=?,updated_at=? WHERE id=?').run(String(name||'').trim(),cents(cost),String(category||'').trim(),active?1:0,String(sku||''),String(notes||''),nextStock,now(),req.params.id); res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}}
app.put('/api/items/:id',requirePermission('page.items'),updateItemRoute);
app.post('/api/items/:id',requirePermission('page.items'),updateItemRoute);
app.get('/api/items/template.csv',requireRole('ADMIN','OWNER'),(req,res)=>{res.type('text/csv').attachment('campstore-items-template.csv').send(itemCsvTemplate())});
app.post('/api/items/import/preview',requireRole('ADMIN','OWNER'),(req,res)=>{const result=validateItemsCsv(req.body?.csv||''); res.json({ok:!result.errors.length,...result,validRows:result.validRows.slice(0,100)})});
app.post('/api/items/import/apply',requireRole('ADMIN','OWNER'),(req,res)=>{const result=validateItemsCsv(req.body?.csv||''); if(result.errors.length) return res.status(400).json({error:'CSV validation failed',errors:result.errors}); res.json({...applyItemsImport(result.validRows,!!req.body?.disableMissing),skipped:result.skipped})});
app.get('/api/stock',requirePermission('page.stock'),(req,res)=>res.json({items:db.prepare(`SELECT i.*, (SELECT max(created_at) FROM stock_adjustments sa WHERE sa.item_id=i.id) last_stock_update FROM items i ORDER BY active DESC, category,name`).all(),recent:db.prepare(`SELECT sa.*,i.name item_name,u.display_name user_display_name FROM stock_adjustments sa JOIN items i ON i.id=sa.item_id LEFT JOIN users u ON u.id=sa.user_id ORDER BY sa.created_at DESC LIMIT 25`).all()}));
app.post('/api/stock/:itemId/add',requirePermission('page.stock'),(req,res)=>{try{const itemId=String(req.params.itemId||''); const raw=req.body?.quantity; if(!/^\d+$/.test(String(raw))) return res.status(400).json({error:'Quantity must be a positive whole number'}); const q=Number(raw); if(!Number.isSafeInteger(q)||q<=0) return res.status(400).json({error:'Quantity must be greater than zero'}); const item=db.prepare('SELECT * FROM items WHERE id=?').get(itemId); if(!item) return res.status(404).json({error:'Item not found'}); const stamp=now(), id='stock_'+nanoid(); let updated; const run=db.transaction(()=>{db.prepare('UPDATE items SET stock_qty=COALESCE(stock_qty,0)+?,updated_at=? WHERE id=?').run(q,stamp,itemId); updated=db.prepare('SELECT stock_qty FROM items WHERE id=?').get(itemId).stock_qty; db.prepare('INSERT INTO stock_adjustments(id,item_id,quantity_change,resulting_quantity,adjustment_type,reason,user_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,itemId,q,updated,'manual_add','Manual stock addition',req.user.id,stamp)}); run(); res.json({ok:true,itemId,quantityAdded:q,stock_qty:updated})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/items/:id/stock',requireRole('ADMIN','OWNER'),(req,res)=>{try{const {action,qty}=req.body||{}; const item=db.prepare('SELECT * FROM items WHERE id=?').get(req.params.id); if(!item) return res.status(404).json({error:'Item not found'}); let next; if(action==='untrack') next=null; else{const n=Math.round(Number(qty)); if(Number.isNaN(n)) throw Error('Quantity must be a number'); if(action==='set') next=n; else if(action==='add') next=(item.stock_qty||0)+n; else if(action==='subtract') next=(item.stock_qty||0)-n; else throw Error('Invalid stock action')} db.prepare('UPDATE items SET stock_qty=?,updated_at=? WHERE id=?').run(next,now(),req.params.id); event('stock_adjust','ok',`${item.name}: ${action} ${action==='untrack'?'':qty} → ${next==null?'untracked':next}`); res.json({ok:true,stock_qty:next})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/campers',requirePermission('page.people'),(req,res)=>res.json(db.prepare('SELECT * FROM campers ORDER BY name').all()));
app.post('/api/campers',requirePermission('page.people'),(req,res)=>{try{const {name,type,person_type,cabin,initial_balance,current_balance,active,notes}=req.body||{}; const trimmed=String(name||'').trim(); if(!trimmed) throw Error('Name is required'); const initial=cents(initial_balance); const current=cents(current_balance); const stamp=now(), id='manual_'+nanoid(); const ptype=validatePersonType(person_type||type); const enabled=active===false?0:1; const run=db.transaction(()=>{db.prepare('INSERT INTO campers(id,name,person_type,initial_balance_cents,current_balance_cents,sheet_row,active,notes,source,cabin,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,trimmed,ptype,initial,current,null,enabled,String(notes||''),'manual',String(cabin||'').trim()||null,stamp); const auditId='audit_'+nanoid(); db.prepare('INSERT INTO audit_logs(id,created_at,admin,action,person_id,person_name,initial_balance_cents,current_balance_cents,details_json) VALUES(?,?,?,?,?,?,?,?,?)').run(auditId,stamp,req.user.displayName,'manual_person_create',id,trimmed,initial,current,JSON.stringify({type:ptype,active:!!enabled,notes:String(notes||'')})); recordOpeningLedger(db,{camperId:id,balanceCents:current,auditLogId:auditId,user:req.user,createdAt:stamp,metadata:{source:'manual_person_create'}})}); run(); res.json({ok:true,id})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/audit-logs',requireRole('ADMIN','OWNER'),(req,res)=>res.json(db.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 200').all()));
function updateCamperRoute(req,res){try{const body=req.body||{}; const {name,type,person_type,cabin,initial_balance,current_balance,active,notes}=body; const camper=db.prepare('SELECT * FROM campers WHERE id=?').get(req.params.id); if(!camper) return res.status(404).json({error:'Person not found'}); if(current_balance!==undefined&&current_balance!==''&&cents(current_balance)!==camper.current_balance_cents) return res.status(400).json({error:'Balance changes must use the adjustment endpoint.'}); if(body.expected_updated_at && camper.updated_at && String(body.expected_updated_at)!==String(camper.updated_at)) return res.status(409).json({error:'This camper was just changed on another device. The list has been refreshed — re-apply your edit.',conflict:true}); const nextName=String(name||'').trim(); if(!nextName) throw Error('Name is required'); const nextInitial=initial_balance!==undefined&&initial_balance!==''?cents(initial_balance):camper.initial_balance_cents; /* TODO Phase 3: make opening balance read-only after creation/import. */ const nextCabin='cabin' in body?(String(cabin||'').trim()||null):camper.cabin; db.prepare('UPDATE campers SET name=?,person_type=?,cabin=?,initial_balance_cents=?,active=?,notes=?,updated_at=? WHERE id=?').run(nextName,validatePersonType(person_type||type||camper.person_type),nextCabin,nextInitial,active?1:0,String(notes||''),now(),req.params.id); res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}}
// Day-of registration: any signed-in user (clerks included) can add a walk-up camper. Registered before :id so it is not shadowed.
app.post('/api/campers/quick-add',(req,res)=>{try{const {name,cabin,person_type,type}=req.body||{}; const trimmed=String(name||'').trim(); if(!trimmed) throw Error('Name is required'); const rawBal=req.body?.initial_balance ?? req.body?.balance ?? req.body?.current_balance ?? 0; const bal=cents(rawBal===''?0:rawBal); const ptype=validatePersonType(person_type||type); const stamp=now(), id='walkin_'+nanoid(); const run=db.transaction(()=>{db.prepare('INSERT INTO campers(id,name,person_type,initial_balance_cents,current_balance_cents,sheet_row,active,notes,source,cabin,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,trimmed,ptype,bal,bal,null,1,'','manual',String(cabin||'').trim()||null,stamp); const auditId='audit_'+nanoid(); db.prepare('INSERT INTO audit_logs(id,created_at,admin,action,person_id,person_name,initial_balance_cents,current_balance_cents,details_json) VALUES(?,?,?,?,?,?,?,?,?)').run(auditId,stamp,req.user.displayName,'walkin_person_create',id,trimmed,bal,bal,JSON.stringify({cabin:String(cabin||'').trim()||null,type:ptype})); recordOpeningLedger(db,{camperId:id,balanceCents:bal,auditLogId:auditId,user:req.user,createdAt:stamp,metadata:{source:'walkin_person_create'}})}); run(); event('walkin_add','ok',`${req.user.displayName} registered ${trimmed}${cabin?` (${String(cabin).trim()})`:''} with ${money(bal)}`); res.json({ok:true,camper:db.prepare('SELECT * FROM campers WHERE id=?').get(id)})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/campers/:id/history',requirePermission('page.people'),(req,res)=>{try{const camper=db.prepare('SELECT id,name,person_type,cabin,initial_balance_cents,current_balance_cents,active FROM campers WHERE id=?').get(req.params.id); if(!camper) return res.status(404).json({error:'Camper not found'}); const requestedLimit=Number.parseInt(String(req.query.limit??'50'),10); const requestedOffset=Number.parseInt(String(req.query.offset??'0'),10); const limit=Math.min(100,Math.max(1,Number.isFinite(requestedLimit)?requestedLimit:50)); const offset=Math.max(0,Number.isFinite(requestedOffset)?requestedOffset:0); const total=db.prepare('SELECT count(*) c FROM account_ledger WHERE camper_id=?').get(camper.id).c; const rows=db.prepare(`SELECT l.*,t.id tx_id,t.camper_id tx_camper_id,t.total_cents tx_total_cents,t.items_json tx_items_json,a.id adj_id,a.camper_id adj_camper_id,a.action adj_action,a.reason adj_reason,a.admin adj_admin,a.amount_cents adj_amount_cents,a.previous_balance_cents adj_previous_balance_cents,a.new_balance_cents adj_new_balance_cents FROM account_ledger l LEFT JOIN transactions t ON t.id=l.transaction_id AND t.camper_id=l.camper_id LEFT JOIN balance_adjustments a ON a.id=l.balance_adjustment_id AND a.camper_id=l.camper_id WHERE l.camper_id=? ORDER BY l.created_at DESC,l.id DESC LIMIT ? OFFSET ?`).all(camper.id,limit,offset); res.json({camper,entries:rows.map(buildHistoryEntry),pagination:{limit,offset,total,has_more:offset+rows.length<total}})}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/campers/:id',requireRole('ADMIN','OWNER'),updateCamperRoute);
app.post('/api/campers/:id',requireRole('ADMIN','OWNER'),updateCamperRoute);
app.post('/api/campers/:id/adjust',requireRole('ADMIN','OWNER'),(req,res)=>{try{const {action,amount,reason}=req.body||{}; if(!String(reason||'').trim()) throw Error('Reason is required'); const camper=db.prepare('SELECT * FROM campers WHERE id=?').get(req.params.id); if(!camper) return res.status(404).json({error:'Camper not found'}); let amt=action==='set'?null:cents(amount); let next=action==='add'?camper.current_balance_cents+amt:action==='subtract'?camper.current_balance_cents-amt:action==='set'?cents(amount):null; if(next===null) throw Error('Invalid adjustment action'); const id='adj_'+nanoid(), stamp=now(); const entryType=action==='add'?'funds_added':action==='subtract'?'funds_subtracted':'balance_set'; const run=db.transaction(()=>{db.prepare('INSERT INTO balance_adjustments(id,created_at,admin,camper_id,camper_name,action,amount_cents,previous_balance_cents,new_balance_cents,reason) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,stamp,req.user.displayName,camper.id,camper.name,action,amt,camper.current_balance_cents,next,String(reason).trim()); applyBalanceChange(db,{camperId:camper.id,entryType,setBalanceCents:next,balanceAdjustmentId:id,reason:String(reason).trim(),user:req.user,createdAt:stamp,metadata:{source:'manual_adjustment',action}})}); run(); res.json({ok:true,id,new_balance_cents:next})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/balance-adjustments',requireRole('ADMIN','OWNER'),(req,res)=>res.json(db.prepare('SELECT * FROM balance_adjustments ORDER BY created_at DESC LIMIT 200').all()));
// Day-of registration: any signed-in user (clerks included) can move campers between cabins.
app.post('/api/campers/:id/cabin',(req,res)=>{try{const camper=db.prepare('SELECT * FROM campers WHERE id=?').get(req.params.id); if(!camper) return res.status(404).json({error:'Camper not found'}); const nextCabin=String(req.body?.cabin||'').trim()||null; const stamp=now(); const run=db.transaction(()=>{db.prepare('UPDATE campers SET cabin=?,updated_at=? WHERE id=?').run(nextCabin,stamp,camper.id); db.prepare('INSERT INTO audit_logs(id,created_at,admin,action,person_id,person_name,initial_balance_cents,current_balance_cents,details_json) VALUES(?,?,?,?,?,?,?,?,?)').run('audit_'+nanoid(),stamp,req.user.displayName,'cabin_move',camper.id,camper.name,camper.initial_balance_cents,camper.current_balance_cents,JSON.stringify({from:camper.cabin||null,to:nextCabin}))}); run(); res.json({ok:true,cabin:nextCabin,updated_at:stamp})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/cabins',(req,res)=>res.json(db.prepare("SELECT COALESCE(NULLIF(TRIM(cabin),''),'') cabin, count(*) c, COALESCE(SUM(current_balance_cents),0) balance FROM campers WHERE active=1 GROUP BY cabin ORDER BY cabin='', cabin").all().map(r=>({cabin:r.cabin||null,count:r.c,balance_cents:r.balance}))));

// Roster / reconciliation import
app.get('/api/roster/template.csv',requireRole('ADMIN','OWNER'),(req,res)=>{res.type('text/csv').attachment('campstore-roster-template.csv').send(rosterTemplate())});
app.post('/api/roster/import/preview',requireRole('ADMIN','OWNER'),(req,res)=>{try{const parsed=parseRosterCsv(req.body?.csv||''); if(!parsed.format) return res.status(400).json({error:parsed.errors[0]||'Unrecognized CSV format',...parsed}); const opts={updateCabins:req.body?.updateCabins!==false,reconcileBalances:req.body?.reconcileBalances!==false,createNew:req.body?.createNew!==false}; const plan=reconcilePlan(parsed,opts); res.json({ok:!plan.errors.length,detected:parsed.detected,format:parsed.format,carriesBalance:parsed.carriesBalance,carriesCabin:parsed.carriesCabin,peopleCount:parsed.people.length,skipped:parsed.skipped,errors:parsed.errors,summary:plan.summary,items:plan.items.slice(0,500)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/roster/import/apply',requireRole('ADMIN','OWNER'),(req,res)=>{try{const parsed=parseRosterCsv(req.body?.csv||''); if(!parsed.format) return res.status(400).json({error:parsed.errors[0]||'Unrecognized CSV format'}); if(parsed.errors.length) return res.status(400).json({error:'CSV has errors',errors:parsed.errors}); const opts={updateCabins:req.body?.updateCabins!==false,reconcileBalances:req.body?.reconcileBalances!==false,createNew:req.body?.createNew!==false}; res.json(applyRoster(parsed,opts,req.user))}catch(e){res.status(400).json({error:e.message})}});

// CSV exports
app.get('/api/export/people.csv',requireRole('ADMIN','OWNER'),(req,res)=>{const rows=db.prepare('SELECT name,person_type,cabin,initial_balance_cents,current_balance_cents,source,external_id,active,notes,updated_at FROM campers ORDER BY cabin,name').all().map(p=>[p.name,p.person_type,p.cabin||'',money(p.initial_balance_cents),money(p.current_balance_cents),p.source,p.external_id||'',p.active?'Yes':'No',p.notes||'',p.updated_at]); sendCsv(res,`campstore-people-${now().slice(0,10)}.csv`,toCsv(['Name','Type','Cabin','Initial Balance','Current Balance','Source','External ID','Active','Notes','Updated'],rows))});
app.get('/api/export/transactions.csv',requireRole('ADMIN','OWNER'),(req,res)=>{const rows=db.prepare('SELECT * FROM transactions ORDER BY created_at DESC').all().map(t=>[t.created_at,t.clerk||'',t.camper_name,money(t.previous_balance_cents),money(t.total_cents),money(t.new_balance_cents),JSON.parse(t.items_json||'[]').map(i=>`${i.qty}x ${i.name} @ $${money(i.price_cents)}`).join('; '),t.sync_status,t.id]); sendCsv(res,`campstore-transactions-${now().slice(0,10)}.csv`,toCsv(['Time','Clerk','Camper','Previous Balance','Total','New Balance','Items','Sync Status','Transaction ID'],rows))});
app.get('/api/export/adjustments.csv',requireRole('ADMIN','OWNER'),(req,res)=>{const rows=db.prepare('SELECT * FROM balance_adjustments ORDER BY created_at DESC').all().map(a=>[a.created_at,a.admin||'',a.camper_name,a.action,a.amount_cents==null?'':money(a.amount_cents),money(a.previous_balance_cents),money(a.new_balance_cents),a.reason,a.sync_status,a.id]); sendCsv(res,`campstore-adjustments-${now().slice(0,10)}.csv`,toCsv(['Time','Admin','Camper','Action','Amount','Previous Balance','New Balance','Reason','Sync Status','Adjustment ID'],rows))});
app.get('/api/export/inventory.csv',requireRole('ADMIN','OWNER'),(req,res)=>{const rows=db.prepare('SELECT name,category,cost_cents,stock_qty,active,sku,notes,updated_at FROM items ORDER BY category,name').all().map(i=>[i.name,i.category,money(i.cost_cents),i.stock_qty==null?'':i.stock_qty,i.active?'Yes':'No',i.sku||'',i.notes||'',i.updated_at]); sendCsv(res,`campstore-inventory-${now().slice(0,10)}.csv`,toCsv(['Item','Category','Cost','Stock','Active','SKU','Notes','Updated'],rows))});

app.get('/api/transactions',requirePermission('page.transactions'),(req,res)=>res.json(db.prepare('SELECT * FROM transactions ORDER BY created_at DESC LIMIT 200').all().map(t=>({...t,items:JSON.parse(t.items_json)}))));
app.post('/api/settings',requireRole('ADMIN','OWNER'),(req,res)=>{for(const [k,v] of Object.entries(req.body||{})) db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v)); res.json({ok:true})});
app.post('/api/sale',(req,res)=>{try{const {camperId, cart, allowOverride}=req.body; const camper=db.prepare('SELECT * FROM campers WHERE id=? AND active=1').get(camperId); if(!camper) return res.status(404).json({error:'Camper not found'}); if(!Array.isArray(cart)||!cart.length) return res.status(400).json({error:'Cart is empty'}); const items=cart.map(ci=>{const item=db.prepare('SELECT * FROM items WHERE id=? AND active=1').get(ci.id); if(!item) throw Error('Item not found'); const qty=Math.max(1,Number(ci.qty)||1); return {id:item.id,name:item.name,price_cents:item.cost_cents,qty,line_total_cents:item.cost_cents*qty}}); const total=items.reduce((a,i)=>a+i.line_total_cents,0); const allow=db.prepare("SELECT value FROM settings WHERE key='allow_over_balance'").get()?.value==='true'; if(camper.current_balance_cents-total<0 && !allow && !allowOverride) return res.status(409).json({error:'Purchase exceeds current balance'}); const txid='tx_'+nanoid(); const created=now(); const run=db.transaction(()=>{db.prepare('INSERT INTO transactions(id,created_at,clerk,camper_id,camper_name,previous_balance_cents,total_cents,new_balance_cents,items_json) VALUES(?,?,?,?,?,?,?,?,?)').run(txid,created,req.user.displayName,camper.id,camper.name,camper.current_balance_cents,total,camper.current_balance_cents-total,JSON.stringify(items)); applyBalanceChange(db,{camperId:camper.id,entryType:'purchase',deltaCents:-total,transactionId:txid,user:req.user,createdAt:created,metadata:{source:'sale',item_count:items.length,total_cents:total}}); for(const it of items){db.prepare('UPDATE items SET stock_qty=stock_qty-? WHERE id=? AND stock_qty IS NOT NULL').run(it.qty,it.id)}}); run(); res.json({ok:true,id:txid,camperId:camper.id,new_balance_cents:camper.current_balance_cents-total})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/settings/google',requireRole('ADMIN','OWNER'),(req,res)=>res.json(googleStatus()));
app.post('/api/settings/google',requireRole('ADMIN','OWNER'),(req,res)=>{try{let {sheetUrl,spreadsheetId,campersSheetName,logsSheetName,serviceAccountEmail,privateKey,serviceAccountJson}=req.body||{}; if(serviceAccountJson){const parsed=typeof serviceAccountJson==='string'?JSON.parse(serviceAccountJson):serviceAccountJson; spreadsheetId=spreadsheetId||parsed.spreadsheet_id||parsed.spreadsheetId; serviceAccountEmail=serviceAccountEmail||parsed.client_email; privateKey=privateKey||parsed.private_key} sheetUrl=String(sheetUrl||spreadsheetId||'').trim(); spreadsheetId=extractSpreadsheetId(spreadsheetId||sheetUrl); campersSheetName=String(campersSheetName||DEFAULT_SHEETS.campers).trim(); logsSheetName=String(logsSheetName||DEFAULT_SHEETS.logs).trim(); serviceAccountEmail=String(serviceAccountEmail||'').trim(); privateKey=String(privateKey||'').trim(); if(!spreadsheetId) return res.status(400).json({error:'Missing Google Sheet URL or spreadsheet ID'}); if(!campersSheetName||!logsSheetName) return res.status(400).json({error:'Missing one or more tab names'}); if(!serviceAccountEmail) return res.status(400).json({error:'Missing service account email'}); if(!privateKey && !getSetting('google_private_key') && !process.env.GOOGLE_PRIVATE_KEY) return res.status(400).json({error:'Missing private key'}); saveSetting('google_sheet_url',sheetUrl); saveSetting('google_spreadsheet_id',spreadsheetId); saveSetting('google_campers_sheet_name',campersSheetName); saveSetting('google_logs_sheet_name',logsSheetName); saveSetting('google_service_account_email',serviceAccountEmail); if(privateKey) saveSetting('google_private_key',privateKey); res.json({ok:true,google:googleStatus()})}catch(e){res.status(400).json({error:'Invalid service account JSON or settings: '+e.message})}});
app.post('/api/google/test',requireRole('ADMIN','OWNER'),async(req,res)=>{try{const {sheets,spreadsheetId,sheetNames}=sheetsClient(); const required=[sheetNames.campers,sheetNames.logs]; const tabs=await validateSheetTabs(sheets,spreadsheetId,required); await verifyEditAccess(sheets,spreadsheetId,sheetNames.logs); event('google_test','ok','Google Sheets connection test succeeded'); res.json({ok:true,message:'Google Sheets connection successful; required tabs exist and edit access verified',tabs,requiredTabs:required,status:googleStatus()})}catch(e){event('google_test','error',e.message); res.status(400).json({error:e.message,status:googleStatus()})}});
app.post('/api/google/import/campers',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await importCampers())}catch(e){event('import_campers','error',e.message); res.status(400).json({error:e.message})}});
app.post('/api/google/sync-pending',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await syncPending())}catch(e){event('sync','error',e.message); db.prepare("UPDATE transactions SET sync_status='error',error=? WHERE sync_status!='synced'").run(e.message); res.status(400).json({error:e.message})}});
app.post('/api/import',requireRole('ADMIN','OWNER'),async(req,res)=>{try{const campers=await importCampers(); res.json({ok:true,campers})}catch(e){event('import','error',e.message); res.status(400).json({error:e.message})}});
app.post('/api/sync',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await syncPending())}catch(e){event('sync','error',e.message); db.prepare("UPDATE transactions SET sync_status='error',error=? WHERE sync_status!='synced'").run(e.message); res.status(400).json({error:e.message})}});
app.get('/api/status',requirePermission('page.admin'),async(req,res)=>{let gs=googleStatus(); const today=new Date().toISOString().slice(0,10); const LOW=Number(process.env.LOW_STOCK_THRESHOLD||5); res.json({database:{path:DB_PATH,ok:true},stats:{campers:db.prepare('SELECT count(*) c FROM campers WHERE active=1').get().c,cabins:db.prepare("SELECT count(*) c FROM (SELECT DISTINCT cabin FROM campers WHERE active=1 AND cabin IS NOT NULL AND TRIM(cabin)!='')").get().c,campersWithoutCabin:db.prepare("SELECT count(*) c FROM campers WHERE active=1 AND (cabin IS NULL OR TRIM(cabin)='')").get().c,items:db.prepare('SELECT count(*) c FROM items WHERE active=1').get().c,itemsByCategory:db.prepare('SELECT category,count(*) c FROM items WHERE active=1 GROUP BY category ORDER BY category').all(),trackedItems:db.prepare('SELECT count(*) c FROM items WHERE active=1 AND stock_qty IS NOT NULL').get().c,lowStock:db.prepare('SELECT count(*) c FROM items WHERE active=1 AND stock_qty IS NOT NULL AND stock_qty<=?').get(LOW).c,outOfStock:db.prepare('SELECT count(*) c FROM items WHERE active=1 AND stock_qty IS NOT NULL AND stock_qty<=0').get().c,lowStockThreshold:LOW,salesToday:db.prepare("SELECT count(*) c FROM transactions WHERE substr(created_at,1,10)=?").get(today).c,revenueToday:db.prepare("SELECT coalesce(sum(total_cents),0) c FROM transactions WHERE substr(created_at,1,10)=?").get(today).c},lastReconcile:getSetting('last_reconcile')||null,googleStatus:gs.configured?'configured':'not configured',google:gs,lastImport:gs.lastImport,lastSync:gs.lastSync,pending:gs.pending,pendingGoogleSync:gs.pendingGoogleSync,version:APP_VERSION,events:db.prepare('SELECT * FROM sync_events ORDER BY id DESC LIMIT 30').all()})});
app.get('/api/users',requirePermission('page.users'),(req,res)=>res.json({pages:PAGE_REGISTRY,users:db.prepare('SELECT id,username,display_name,role,active,created_at,updated_at FROM users ORDER BY username').all().map(u=>({...u,permissionOverrides:permissionOverrides(u.id),effectivePermissions:getEffectivePermissions({id:u.id,role:u.role})}))}));
app.post('/api/users',requirePermission('page.users'),(req,res)=>{const {username,password,displayName,role}=req.body||{}; if(role==='OWNER'&&req.user.role!=='OWNER') return res.status(403).json({error:'Only OWNER can create OWNER accounts'}); if(!username||!password||!ROLES[role]) return res.status(400).json({error:'username, password, and role are required'}); const stamp=now(); db.prepare('INSERT INTO users(id,username,display_name,role,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('user_'+nanoid(),username,displayName||username,role,hashPassword(password),1,stamp,stamp); res.json({ok:true})});
app.post('/api/users/:id/permissions',requirePermission('page.users'),(req,res)=>{try{const target=db.prepare('SELECT id,role,active FROM users WHERE id=?').get(req.params.id); if(!target) return res.status(404).json({error:'User not found'}); if(req.user.role!=='OWNER' && target.role==='OWNER') return res.status(403).json({error:'Only OWNER can modify OWNER accounts'}); const permissions=req.body?.permissions||{}; const stamp=now(); const run=db.transaction(()=>{db.prepare('DELETE FROM user_page_permissions WHERE user_id=?').run(target.id); for(const [key,val] of Object.entries(permissions)){if(!PAGE_KEYS.has(key)) continue; if(target.role==='OWNER') continue; if(val==='allow'||val===true||val===1) db.prepare('INSERT INTO user_page_permissions(user_id,permission_key,allowed,created_at,updated_at) VALUES(?,?,?,?,?)').run(target.id,key,1,stamp,stamp); else if(val==='deny'||val===false||val===0) db.prepare('INSERT INTO user_page_permissions(user_id,permission_key,allowed,created_at,updated_at) VALUES(?,?,?,?,?)').run(target.id,key,0,stamp,stamp)}}); run(); res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/users/:id/status',requirePermission('page.users'),(req,res)=>{try{if(isFinalActiveOwner(req.params.id) && req.body?.active===false) return res.status(400).json({error:'Cannot disable the final active OWNER'}); db.prepare('UPDATE users SET active=?,updated_at=? WHERE id=?').run(req.body?.active===false?0:1,now(),req.params.id); res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/users/:id/password',requireRole('OWNER'),(req,res)=>{if(!req.body?.password) return res.status(400).json({error:'password is required'}); db.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').run(hashPassword(req.body.password),now(),req.params.id); res.json({ok:true})});
if (require.main === module) app.listen(process.env.PORT||3077,()=>console.log(`Camp Store POS running on ${process.env.PORT||3077}`));
module.exports = { app, db, hashPassword, migrate, seedDefaultOwner, initialSeedResult: INITIAL_SEED_RESULT, parseRosterCsv, reconcilePlan, PAGE_REGISTRY, getEffectivePermissions, userHasPermission };
