const fs = require('fs');
const path = require('path');
if (fs.existsSync(path.join(__dirname, 'node_modules', 'dotenv'))) require('dotenv').config();
else if (fs.existsSync(path.join(__dirname, '.env'))) require('./scripts/env').loadEnv();
const express = require('express');
const { google } = require('googleapis');
const Database = require('better-sqlite3');
const { randomUUID, randomBytes, scryptSync, timingSafeEqual, createHmac } = require('crypto');
const nanoid = () => randomUUID().replace(/-/g, '').slice(0, 21);
const APP_VERSION = process.env.APP_VERSION || readCommit() || 'dev';
const DB_PATH = process.env.DATABASE_PATH || './data/campstore.sqlite';
const SESSION_SECRET = process.env.SESSION_SECRET || process.env.DEFAULT_OWNER_PASSWORD || 'campstore-dev-session-secret';
const ROLES = { OWNER: 3, ADMIN: 2, CLERK: 1 };
fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });
const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');
migrate();
const INITIAL_SEED_RESULT = seedDefaultOwner();
const app = express();
app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: false }));
function readCommit(){try{return require('child_process').execSync('git rev-parse --short HEAD',{stdio:['ignore','pipe','ignore']}).toString().trim()}catch{return null}}
function migrate(){
 db.exec(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS items(id TEXT PRIMARY KEY,name TEXT NOT NULL,cost_cents INTEGER NOT NULL,category TEXT NOT NULL DEFAULT 'Uncategorized',active INTEGER NOT NULL DEFAULT 1,sku TEXT,notes TEXT,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS campers(id TEXT PRIMARY KEY,name TEXT NOT NULL,person_type TEXT NOT NULL DEFAULT 'Camper',initial_balance_cents INTEGER NOT NULL,current_balance_cents INTEGER NOT NULL,sheet_row INTEGER,active INTEGER NOT NULL DEFAULT 1,notes TEXT,source TEXT NOT NULL DEFAULT 'google',updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,clerk TEXT,camper_id TEXT NOT NULL,camper_name TEXT NOT NULL,previous_balance_cents INTEGER NOT NULL,total_cents INTEGER NOT NULL,new_balance_cents INTEGER NOT NULL,items_json TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',synced_at TEXT,error TEXT,FOREIGN KEY(camper_id) REFERENCES campers(id));
 CREATE TABLE IF NOT EXISTS sync_events(id INTEGER PRIMARY KEY AUTOINCREMENT,created_at TEXT NOT NULL,type TEXT NOT NULL,status TEXT NOT NULL,message TEXT);
 CREATE TABLE IF NOT EXISTS balance_adjustments(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,admin TEXT,camper_id TEXT NOT NULL,camper_name TEXT NOT NULL,action TEXT NOT NULL,amount_cents INTEGER,previous_balance_cents INTEGER NOT NULL,new_balance_cents INTEGER NOT NULL,reason TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',synced_at TEXT,error TEXT);
 CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,admin TEXT,action TEXT NOT NULL,person_id TEXT,person_name TEXT,initial_balance_cents INTEGER,current_balance_cents INTEGER,details_json TEXT);
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('OWNER','ADMIN','CLERK')),password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);`);

 // Existing databases may have older tables. Add columns before any SQL below
 // references them (especially items.category in the category index/status queries).
 ensureColumn('items','category',"TEXT NOT NULL DEFAULT 'Uncategorized'");
 ensureColumn('items','active',"INTEGER NOT NULL DEFAULT 1");
 ensureColumn('items','sku',"TEXT");
 ensureColumn('items','notes',"TEXT");
 ensureColumn('campers','person_type',"TEXT NOT NULL DEFAULT 'Camper'");
 ensureColumn('campers','active',"INTEGER NOT NULL DEFAULT 1");
 ensureColumn('campers','notes',"TEXT");
 ensureColumn('campers','source',"TEXT NOT NULL DEFAULT 'google'");
 ensureColumn('users','active',"INTEGER NOT NULL DEFAULT 1");

 db.exec(`CREATE INDEX IF NOT EXISTS idx_campers_name ON campers(name);
 CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);`);
 ensureItemsNameCategoryIndex();
 setDefault('allow_over_balance', String(process.env.ALLOW_OVER_BALANCE === 'true'));
}
function tableColumns(table){return db.prepare(`PRAGMA table_info(${table})`).all().map(c=>c.name)}
function ensureColumn(table,column,definition){const cols=tableColumns(table); if(!cols.includes(column)){db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`); console.log(`[migration] Added ${table}.${column}`)} else console.log(`[migration] ${table}.${column} already exists`)}
function ensureItemsNameCategoryIndex(){const duplicates=db.prepare('SELECT lower(name) name_key, lower(category) category_key, count(*) c FROM items GROUP BY lower(name), lower(category) HAVING c > 1 LIMIT 1').get(); if(duplicates){console.log('[migration] Skipped idx_items_name_category because duplicate item names/categories already exist'); return} db.exec('CREATE UNIQUE INDEX IF NOT EXISTS idx_items_name_category ON items(lower(name),lower(category))'); console.log('[migration] Ensured idx_items_name_category')}
function setDefault(k,v){db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v)}
function seedDefaultOwner(){const existingCount=db.prepare('SELECT count(*) c FROM users').get().c; if(existingCount>0) return {seeded:false,reason:'users-exist'}; const username=process.env.DEFAULT_OWNER_USERNAME, password=process.env.DEFAULT_OWNER_PASSWORD; if(!username||!password) return {seeded:false,reason:'missing-env'}; const display=process.env.DEFAULT_OWNER_DISPLAY_NAME||username; const stamp=now(); db.prepare('INSERT INTO users(id,username,display_name,role,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('user_'+nanoid(),username,display,'OWNER',hashPassword(password),1,stamp,stamp); return {seeded:true,username}}
function hashPassword(password){const salt=randomBytes(16).toString('hex'); const hash=scryptSync(password,salt,64).toString('hex'); return `scrypt$${salt}$${hash}`}
function verifyPassword(password,stored){const [scheme,salt,hash]=String(stored||'').split('$'); if(scheme!=='scrypt'||!salt||!hash) return false; const actual=Buffer.from(hash,'hex'); const check=scryptSync(password,salt,64); return actual.length===check.length && timingSafeEqual(actual,check)}
function sign(value){return createHmac('sha256',SESSION_SECRET).update(value).digest('base64url')}
function makeSession(user){const payload=Buffer.from(JSON.stringify({id:user.id,username:user.username,displayName:user.display_name,role:user.role,exp:Date.now()+1000*60*60*12})).toString('base64url'); return `${payload}.${sign(payload)}`}
function parseCookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').filter(Boolean).map(p=>{const i=p.indexOf('='); return [p.slice(0,i).trim(),decodeURIComponent(p.slice(i+1))]}))}
function currentUser(req){const token=parseCookies(req).campstore_session; if(!token) return null; const [payload,sig]=token.split('.'); if(!payload||sig!==sign(payload)) return null; try{const data=JSON.parse(Buffer.from(payload,'base64url').toString()); if(data.exp<Date.now()) return null; const user=db.prepare('SELECT id,username,display_name,role,active FROM users WHERE id=? AND active=1').get(data.id); return user?{id:user.id,username:user.username,displayName:user.display_name,role:user.role}:null}catch{return null}}
function requireAuth(req,res,next){const user=currentUser(req); if(!user) return wantsHtml(req)?res.redirect('/login.html'):res.status(401).json({error:'Authentication required'}); req.user=user; next()}
function requireRole(...roles){return (req,res,next)=>{if(!req.user) return requireAuth(req,res,()=>requireRole(...roles)(req,res,next)); const min=Math.min(...roles.map(r=>ROLES[r])); if(ROLES[req.user.role]<min) return wantsHtml(req)?res.status(403).send('Forbidden'):res.status(403).json({error:'Forbidden'}); next()}}
function wantsHtml(req){return (req.headers.accept||'').includes('text/html') || !(req.originalUrl||req.path).startsWith('/api/')}
function cents(v){ if (typeof v === 'number') return Math.round(v*100); const s=String(v||'').replace(/[$,]/g,'').trim(); if(!s) throw Error('missing money value'); const n=Number(s); if(Number.isNaN(n)) throw Error('invalid money value '+v); return Math.round(n*100)}
function money(c){return (c/100).toFixed(2)}
function now(){return new Date().toISOString()}

function getSetting(key){return db.prepare('SELECT value FROM settings WHERE key=?').get(key)?.value||''}
function saveSetting(key,value){db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,String(value||''))}
const DEFAULT_SHEETS = { campers: 'Campers / Balances', logs: 'Logs' };
function extractSpreadsheetId(input){
 const value=String(input||'').trim();
 if(!value) return '';
 const match=value.match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);
 if(match) return match[1];
 return value;
}
function quoteSheetName(name){return `'${String(name).replace(/'/g,"''")}'`}
function googleConfig(){
 const sheetUrl=getSetting('google_sheet_url')||process.env.GOOGLE_SHEET_URL||'';
 const savedId=getSetting('google_spreadsheet_id')||process.env.GOOGLE_SPREADSHEET_ID||'';
 const spreadsheetId=extractSpreadsheetId(savedId||sheetUrl);
 const sheetNames={
  campers:getSetting('google_campers_sheet_name')||process.env.GOOGLE_CAMPERS_SHEET_NAME||DEFAULT_SHEETS.campers,
  logs:getSetting('google_logs_sheet_name')||process.env.GOOGLE_LOGS_SHEET_NAME||DEFAULT_SHEETS.logs
 };
 const email=getSetting('google_service_account_email')||process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||'';
 const rawKey=getSetting('google_private_key')||process.env.GOOGLE_PRIVATE_KEY||'';
 const privateKey=rawKey.replace(/\\n/g,'\n');
 return {sheetUrl,spreadsheetId,sheetNames,email,privateKey,source:getSetting('google_spreadsheet_id')?'database':'env'};
}
function googleStatus(){const c=googleConfig(); const pendingTransactions=db.prepare("SELECT count(*) c FROM transactions WHERE sync_status!='synced'").get().c; const pendingAdjustments=db.prepare("SELECT count(*) c FROM balance_adjustments WHERE sync_status!='synced'").get().c; return {configured:!!(c.spreadsheetId&&c.email&&c.privateKey),sheetUrl:c.sheetUrl||'',spreadsheetId:c.spreadsheetId?`configured · ${String(c.spreadsheetId).slice(-4)}`:'missing',spreadsheetIdValue:c.spreadsheetId||'',sheetNames:c.sheetNames,serviceAccountEmail:c.email||'',privateKey:c.privateKey?`configured · ${String(c.privateKey).replace(/\n/g,'').slice(-4)}`:'missing',source:c.source,lastImport:getSetting('last_import')||null,lastSync:getSetting('last_sync')||null,pending:pendingTransactions+pendingAdjustments,pendingTransactions,pendingAdjustments}}
function sheetsClient(){ const c=googleConfig(); if(!c.spreadsheetId) throw Error('Missing spreadsheet ID or Google Sheet URL'); if(!c.email) throw Error('Missing service account email'); if(!c.privateKey) throw Error('Missing private key'); const auth = new google.auth.JWT(c.email, null, c.privateKey, ['https://www.googleapis.com/auth/spreadsheets']); return {sheets:google.sheets({version:'v4', auth}), spreadsheetId:c.spreadsheetId,sheetNames:c.sheetNames};}
async function validateSheetTabs(sheets,spreadsheetId,required){const meta=await sheets.spreadsheets.get({spreadsheetId,fields:'sheets.properties.title'}); const tabs=new Set((meta.data.sheets||[]).map(s=>s.properties.title)); const needed=required||[googleConfig().sheetNames.campers,googleConfig().sheetNames.logs]; const missing=needed.filter(t=>!tabs.has(t)); if(missing.length) throw Error('Invalid tab names. Missing required tab(s): '+missing.join(', ')); return [...tabs]}
async function verifyEditAccess(sheets,spreadsheetId,sheetName){const range=`${quoteSheetName(sheetName)}!A1`; const current=await sheets.spreadsheets.values.get({spreadsheetId,range}); const value=current.data.values?.[0]?.[0]||''; await sheets.spreadsheets.values.update({spreadsheetId,range,valueInputOption:'USER_ENTERED',requestBody:{values:[[value]]}})}
function parseMoneyCell(value,label){try{return cents(value)}catch(e){throw Error(`${label}: ${e.message}`)}}
function parseCsv(text){
 const rows=[]; let row=[], cell='', inQuotes=false; const data=String(text||'').replace(/^\ufeff/,'');
 for(let i=0;i<data.length;i++){const ch=data[i], next=data[i+1]; if(inQuotes){if(ch==='"'&&next==='"'){cell+='"'; i++} else if(ch==='"') inQuotes=false; else cell+=ch} else if(ch==='"') inQuotes=true; else if(ch===','){row.push(cell); cell=''} else if(ch==='\n'){row.push(cell); rows.push(row); row=[]; cell=''} else if(ch==='\r'){} else cell+=ch}
 row.push(cell); if(row.some(v=>String(v).trim()!=='')) rows.push(row); return rows;
}
function itemCsvTemplate(){return 'Cost,Item Name,Category,Active,SKU,Notes\n1.50,Snack,Food,true,SNACK-001,Example item\n'}
function validateItemsCsv(text){
 const rows=parseCsv(text); if(!rows.length) return {headers:[],validRows:[],errors:['CSV is empty'],skipped:0};
 const headers=rows[0].map(h=>String(h).trim()); const idx=Object.fromEntries(headers.map((h,i)=>[h.toLowerCase(),i]));
 const req=['cost','item name','category'], errors=[], validRows=[], seen=new Set(); let skipped=0;
 for(const h of req) if(idx[h]===undefined) errors.push(`Missing required column: ${h==='cost'?'Cost':h==='item name'?'Item Name':'Category'}`);
 if(errors.length) return {headers,validRows,errors,skipped};
 for(const [n,row] of rows.slice(1).entries()){const rowNum=n+2; if(row.every(c=>String(c||'').trim()==='')){skipped++; continue}
  const name=String(row[idx['item name']]||'').trim(), category=String(row[idx.category]||'').trim(), rawCost=String(row[idx.cost]||'').trim();
  if(!rawCost) errors.push(`Row ${rowNum}: missing Cost`); let cost=null; if(rawCost) try{cost=cents(rawCost)}catch{errors.push(`Row ${rowNum}: invalid Cost`)}
  if(!name) errors.push(`Row ${rowNum}: missing Item Name`); if(!category) errors.push(`Row ${rowNum}: missing Category`);
  const key=`${name.toLowerCase()}|${category.toLowerCase()}`; if(name&&category&&seen.has(key)) errors.push(`Row ${rowNum}: duplicate item name in same category (${name} / ${category})`); seen.add(key);
  if(name&&category&&cost!==null) validRows.push({name,category,cost_cents:cost,active:parseBool(row[idx.active],true),sku:String(row[idx.sku]||'').trim(),notes:String(row[idx.notes]||'').trim()});
 }
 return {headers,validRows,errors,skipped};
}
function validatePersonType(value){const type=String(value||'Camper').trim(); return ['Camper','Staff','Other'].includes(type)?type:'Other'}
function parseBool(v,def=true){const s=String(v??'').trim().toLowerCase(); if(!s) return def; return ['1','true','yes','y','active','enabled'].includes(s)?1:0}
function applyItemsImport(validRows,disableMissing){const stamp=now(); const keep=[]; const run=db.transaction(()=>{for(const item of validRows){const existing=db.prepare('SELECT id FROM items WHERE lower(name)=lower(?) AND lower(category)=lower(?)').get(item.name,item.category); const id=existing?.id||'item_'+nanoid(); keep.push(id); db.prepare('INSERT INTO items(id,name,cost_cents,category,active,sku,notes,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,cost_cents=excluded.cost_cents,category=excluded.category,active=excluded.active,sku=excluded.sku,notes=excluded.notes,updated_at=excluded.updated_at').run(id,item.name,item.cost_cents,item.category,item.active,item.sku,item.notes,stamp)} if(disableMissing&&keep.length) db.prepare(`UPDATE items SET active=0,updated_at=? WHERE id NOT IN (${keep.map(()=>'?').join(',')})`).run(stamp,...keep)}); run(); event('import_items_csv','ok',`Imported ${validRows.length} CSV items${disableMissing?'; disabled missing items':''}`); return {ok:true,imported:validRows.length,disabledMissing:!!disableMissing,lastImport:stamp}}
async function importCampers(){const {sheets,spreadsheetId,sheetNames}=sheetsClient(); await validateSheetTabs(sheets,spreadsheetId,[sheetNames.campers]); const r=await sheets.spreadsheets.values.get({spreadsheetId,range:`${quoteSheetName(sheetNames.campers)}!A2:C`}); const rows=r.data.values||[], seen=new Set(), warnings=[]; const stamp=now(); let imported=0, skipped=0; const run=db.transaction(()=>{for(const [i,row] of rows.entries()){if(!row[0]&&!row[1]&&!row[2]){skipped++; continue} if(!row[0]) throw Error(`${sheetNames.campers} row ${i+2}: missing child name`); const name=String(row[0]).trim(); const key=name.toLowerCase(); if(seen.has(key)) throw Error('Duplicate camper name: '+name); seen.add(key); const initial=parseMoneyCell(row[1],`${sheetNames.campers} row ${i+2} initial balance`); const current=parseMoneyCell(row[2],`${sheetNames.campers} row ${i+2} current balance`); const existing=db.prepare('SELECT id FROM campers WHERE lower(name)=lower(?) ORDER BY source=\'manual\' DESC LIMIT 1').get(name); const id=existing?.id||'camper_'+Buffer.from(key).toString('hex').slice(0,32); db.prepare('INSERT INTO campers(id,name,person_type,initial_balance_cents,current_balance_cents,sheet_row,active,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,person_type=COALESCE(campers.person_type, excluded.person_type),initial_balance_cents=excluded.initial_balance_cents,current_balance_cents=excluded.current_balance_cents,sheet_row=excluded.sheet_row,active=1,source=excluded.source,updated_at=excluded.updated_at').run(id,name,'Camper',initial,current,i+2,1,'google',stamp); imported++}}); run(); saveSetting('last_import',stamp); event('import_campers','ok',`Imported ${imported} campers; skipped ${skipped} blank rows`); return {ok:true,imported,skipped,warnings,lastImport:stamp}}
async function syncPending(){const {sheets,spreadsheetId,sheetNames}=sheetsClient(); await validateSheetTabs(sheets,spreadsheetId,[sheetNames.campers,sheetNames.logs]); const pending=db.prepare("SELECT * FROM transactions WHERE sync_status!='synced' ORDER BY created_at").all(); const adjustments=db.prepare("SELECT * FROM balance_adjustments WHERE sync_status!='synced' ORDER BY created_at").all(); for(const t of pending){await sheets.spreadsheets.values.append({spreadsheetId,range:`${quoteSheetName(sheetNames.logs)}!A:I`,valueInputOption:'USER_ENTERED',requestBody:{values:[[t.created_at,t.clerk,t.camper_name,money(t.previous_balance_cents),money(t.total_cents),money(t.new_balance_cents),JSON.parse(t.items_json).map(i=>`${i.qty}x ${i.name} @ $${money(i.price_cents)}`).join('; '),t.id,'sale']]}}); const camper=db.prepare('SELECT sheet_row FROM campers WHERE id=?').get(t.camper_id); if(camper?.sheet_row) await sheets.spreadsheets.values.update({spreadsheetId,range:`${quoteSheetName(sheetNames.campers)}!C${camper.sheet_row}`,valueInputOption:'USER_ENTERED',requestBody:{values:[[money(t.new_balance_cents)]]}}); db.prepare("UPDATE transactions SET sync_status='synced',synced_at=?,error=NULL WHERE id=?").run(now(),t.id)} for(const a of adjustments){await sheets.spreadsheets.values.append({spreadsheetId,range:`${quoteSheetName(sheetNames.logs)}!A:I`,valueInputOption:'USER_ENTERED',requestBody:{values:[[a.created_at,a.admin,a.camper_name,money(a.previous_balance_cents),a.amount_cents==null?'':money(a.amount_cents),money(a.new_balance_cents),`${a.action}: ${a.reason}`,a.id,'balance_adjustment']]}}); const camper=db.prepare('SELECT sheet_row FROM campers WHERE id=?').get(a.camper_id); if(camper?.sheet_row) await sheets.spreadsheets.values.update({spreadsheetId,range:`${quoteSheetName(sheetNames.campers)}!C${camper.sheet_row}`,valueInputOption:'USER_ENTERED',requestBody:{values:[[money(a.new_balance_cents)]]}}); db.prepare("UPDATE balance_adjustments SET sync_status='synced',synced_at=?,error=NULL WHERE id=?").run(now(),a.id)} const stamp=now(); saveSetting('last_sync',stamp); event('sync','ok',`Synced ${pending.length} transactions and ${adjustments.length} adjustments`); return {ok:true,synced:pending.length,adjustmentsSynced:adjustments.length,lastSync:stamp}}
function event(type,status,message){db.prepare('INSERT INTO sync_events(created_at,type,status,message) VALUES(?,?,?,?)').run(now(),type,status,message||'')}
app.get('/login.html',(req,res)=>res.sendFile(path.join(__dirname,'public','login.html')));
app.get('/login',(req,res)=>res.redirect('/login.html'));
app.post('/api/login',(req,res)=>{const {username,password}=req.body||{}; const user=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(String(username||'')); if(!user||!verifyPassword(String(password||''),user.password_hash)) return res.status(401).json({error:'Invalid username or password'}); res.cookie('campstore_session',makeSession(user),{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true',maxAge:1000*60*60*12}); res.json({ok:true,user:{username:user.username,displayName:user.display_name,role:user.role}})});
app.post('/api/logout',(req,res)=>{res.clearCookie('campstore_session'); res.json({ok:true})});
app.get('/api/me',requireAuth,(req,res)=>res.json({user:req.user}));
app.get('/',requireAuth,(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.get('/index.html',requireAuth,(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.get('/admin.html',requireAuth,requireRole('ADMIN','OWNER'),(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
app.use(express.static(path.join(__dirname, 'public'), { index: false }));
app.use('/api',requireAuth);
app.get('/api/state',(req,res)=>{res.json({user:req.user,items:db.prepare('SELECT * FROM items WHERE active=1 ORDER BY name').all(),campers:db.prepare('SELECT * FROM campers WHERE active=1 ORDER BY name').all(),settings:Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(r=>[r.key,r.value])),pending:db.prepare("SELECT count(*) c FROM transactions WHERE sync_status!='synced'").get().c,version:APP_VERSION})});

app.get('/api/items',requireRole('ADMIN','OWNER'),(req,res)=>res.json(db.prepare('SELECT * FROM items ORDER BY category,name').all()));
app.post('/api/items',requireRole('ADMIN','OWNER'),(req,res)=>{try{const {name,cost,category,active,sku,notes}=req.body||{}; if(!String(name||'').trim()) throw Error('Item name is required'); if(!String(category||'').trim()) throw Error('Category is required'); const stamp=now(); db.prepare('INSERT INTO items(id,name,cost_cents,category,active,sku,notes,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('item_'+nanoid(),String(name).trim(),cents(cost),String(category).trim(),active===false?0:1,String(sku||''),String(notes||''),stamp); res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
function updateItemRoute(req,res){try{const {name,cost,category,active,sku,notes}=req.body||{}; db.prepare('UPDATE items SET name=?,cost_cents=?,category=?,active=?,sku=?,notes=?,updated_at=? WHERE id=?').run(String(name||'').trim(),cents(cost),String(category||'').trim(),active?1:0,String(sku||''),String(notes||''),now(),req.params.id); res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}}
app.put('/api/items/:id',requireRole('ADMIN','OWNER'),updateItemRoute);
app.post('/api/items/:id',requireRole('ADMIN','OWNER'),updateItemRoute);
app.get('/api/items/template.csv',requireRole('ADMIN','OWNER'),(req,res)=>{res.type('text/csv').attachment('campstore-items-template.csv').send(itemCsvTemplate())});
app.post('/api/items/import/preview',requireRole('ADMIN','OWNER'),(req,res)=>{const result=validateItemsCsv(req.body?.csv||''); res.json({ok:!result.errors.length,...result,validRows:result.validRows.slice(0,100)})});
app.post('/api/items/import/apply',requireRole('ADMIN','OWNER'),(req,res)=>{const result=validateItemsCsv(req.body?.csv||''); if(result.errors.length) return res.status(400).json({error:'CSV validation failed',errors:result.errors}); res.json({...applyItemsImport(result.validRows,!!req.body?.disableMissing),skipped:result.skipped})});
app.get('/api/campers',requireRole('ADMIN','OWNER'),(req,res)=>res.json(db.prepare('SELECT * FROM campers ORDER BY name').all()));
app.post('/api/campers',requireRole('ADMIN','OWNER'),(req,res)=>{try{const {name,type,person_type,initial_balance,current_balance,active,notes}=req.body||{}; const trimmed=String(name||'').trim(); if(!trimmed) throw Error('Name is required'); const initial=cents(initial_balance); const current=cents(current_balance); const stamp=now(), id='manual_'+nanoid(); const ptype=validatePersonType(person_type||type); const enabled=active===false?0:1; const run=db.transaction(()=>{db.prepare('INSERT INTO campers(id,name,person_type,initial_balance_cents,current_balance_cents,sheet_row,active,notes,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,trimmed,ptype,initial,current,null,enabled,String(notes||''),'manual',stamp); db.prepare('INSERT INTO audit_logs(id,created_at,admin,action,person_id,person_name,initial_balance_cents,current_balance_cents,details_json) VALUES(?,?,?,?,?,?,?,?,?)').run('audit_'+nanoid(),stamp,req.user.displayName,'manual_person_create',id,trimmed,initial,current,JSON.stringify({type:ptype,active:!!enabled,notes:String(notes||'')}))}); run(); res.json({ok:true,id})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/audit-logs',requireRole('ADMIN','OWNER'),(req,res)=>res.json(db.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 200').all()));
function updateCamperRoute(req,res){try{const {name,type,person_type,initial_balance,current_balance,active,notes}=req.body||{}; const camper=db.prepare('SELECT * FROM campers WHERE id=?').get(req.params.id); if(!camper) return res.status(404).json({error:'Person not found'}); const nextName=String(name||'').trim(); if(!nextName) throw Error('Name is required'); const nextInitial=initial_balance!==undefined&&initial_balance!==''?cents(initial_balance):camper.initial_balance_cents; const nextCurrent=current_balance!==undefined&&current_balance!==''?cents(current_balance):camper.current_balance_cents; db.prepare('UPDATE campers SET name=?,person_type=?,initial_balance_cents=?,current_balance_cents=?,active=?,notes=?,updated_at=? WHERE id=?').run(nextName,validatePersonType(person_type||type||camper.person_type),nextInitial,nextCurrent,active?1:0,String(notes||''),now(),req.params.id); res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}}
app.put('/api/campers/:id',requireRole('ADMIN','OWNER'),updateCamperRoute);
app.post('/api/campers/:id',requireRole('ADMIN','OWNER'),updateCamperRoute);
app.post('/api/campers/:id/adjust',requireRole('ADMIN','OWNER'),(req,res)=>{try{const {action,amount,reason}=req.body||{}; if(!String(reason||'').trim()) throw Error('Reason is required'); const camper=db.prepare('SELECT * FROM campers WHERE id=?').get(req.params.id); if(!camper) return res.status(404).json({error:'Camper not found'}); let amt=action==='set'?null:cents(amount); let next=action==='add'?camper.current_balance_cents+amt:action==='subtract'?camper.current_balance_cents-amt:action==='set'?cents(amount):null; if(next===null) throw Error('Invalid adjustment action'); const id='adj_'+nanoid(), stamp=now(); const run=db.transaction(()=>{db.prepare('UPDATE campers SET current_balance_cents=?,updated_at=? WHERE id=?').run(next,stamp,camper.id); db.prepare('INSERT INTO balance_adjustments(id,created_at,admin,camper_id,camper_name,action,amount_cents,previous_balance_cents,new_balance_cents,reason) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,stamp,req.user.displayName,camper.id,camper.name,action,amt,camper.current_balance_cents,next,String(reason).trim())}); run(); res.json({ok:true,id,new_balance_cents:next})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/balance-adjustments',requireRole('ADMIN','OWNER'),(req,res)=>res.json(db.prepare('SELECT * FROM balance_adjustments ORDER BY created_at DESC LIMIT 200').all()));

app.get('/api/transactions',requireRole('ADMIN','OWNER'),(req,res)=>res.json(db.prepare('SELECT * FROM transactions ORDER BY created_at DESC LIMIT 200').all().map(t=>({...t,items:JSON.parse(t.items_json)}))));
app.post('/api/settings',requireRole('ADMIN','OWNER'),(req,res)=>{for(const [k,v] of Object.entries(req.body||{})) db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v)); res.json({ok:true})});
app.post('/api/sale',(req,res)=>{try{const {camperId, cart, allowOverride}=req.body; const camper=db.prepare('SELECT * FROM campers WHERE id=? AND active=1').get(camperId); if(!camper) return res.status(404).json({error:'Camper not found'}); if(!Array.isArray(cart)||!cart.length) return res.status(400).json({error:'Cart is empty'}); const items=cart.map(ci=>{const item=db.prepare('SELECT * FROM items WHERE id=? AND active=1').get(ci.id); if(!item) throw Error('Item not found'); const qty=Math.max(1,Number(ci.qty)||1); return {id:item.id,name:item.name,price_cents:item.cost_cents,qty,line_total_cents:item.cost_cents*qty}}); const total=items.reduce((a,i)=>a+i.line_total_cents,0); const allow=db.prepare("SELECT value FROM settings WHERE key='allow_over_balance'").get()?.value==='true'; if(camper.current_balance_cents-total<0 && !allow && !allowOverride) return res.status(409).json({error:'Purchase exceeds current balance'}); const txid='tx_'+nanoid(); const created=now(); const run=db.transaction(()=>{db.prepare('UPDATE campers SET current_balance_cents=?,updated_at=? WHERE id=?').run(camper.current_balance_cents-total,created,camper.id); db.prepare('INSERT INTO transactions(id,created_at,clerk,camper_id,camper_name,previous_balance_cents,total_cents,new_balance_cents,items_json) VALUES(?,?,?,?,?,?,?,?,?)').run(txid,created,req.user.displayName,camper.id,camper.name,camper.current_balance_cents,total,camper.current_balance_cents-total,JSON.stringify(items));}); run(); res.json({ok:true,id:txid,camperId:camper.id,new_balance_cents:camper.current_balance_cents-total})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/settings/google',requireRole('ADMIN','OWNER'),(req,res)=>res.json(googleStatus()));
app.post('/api/settings/google',requireRole('ADMIN','OWNER'),(req,res)=>{try{let {sheetUrl,spreadsheetId,campersSheetName,logsSheetName,serviceAccountEmail,privateKey,serviceAccountJson}=req.body||{}; if(serviceAccountJson){const parsed=typeof serviceAccountJson==='string'?JSON.parse(serviceAccountJson):serviceAccountJson; spreadsheetId=spreadsheetId||parsed.spreadsheet_id||parsed.spreadsheetId; serviceAccountEmail=serviceAccountEmail||parsed.client_email; privateKey=privateKey||parsed.private_key} sheetUrl=String(sheetUrl||spreadsheetId||'').trim(); spreadsheetId=extractSpreadsheetId(spreadsheetId||sheetUrl); campersSheetName=String(campersSheetName||DEFAULT_SHEETS.campers).trim(); logsSheetName=String(logsSheetName||DEFAULT_SHEETS.logs).trim(); serviceAccountEmail=String(serviceAccountEmail||'').trim(); privateKey=String(privateKey||'').trim(); if(!spreadsheetId) return res.status(400).json({error:'Missing Google Sheet URL or spreadsheet ID'}); if(!campersSheetName||!logsSheetName) return res.status(400).json({error:'Missing one or more tab names'}); if(!serviceAccountEmail) return res.status(400).json({error:'Missing service account email'}); if(!privateKey && !getSetting('google_private_key') && !process.env.GOOGLE_PRIVATE_KEY) return res.status(400).json({error:'Missing private key'}); saveSetting('google_sheet_url',sheetUrl); saveSetting('google_spreadsheet_id',spreadsheetId); saveSetting('google_campers_sheet_name',campersSheetName); saveSetting('google_logs_sheet_name',logsSheetName); saveSetting('google_service_account_email',serviceAccountEmail); if(privateKey) saveSetting('google_private_key',privateKey); res.json({ok:true,google:googleStatus()})}catch(e){res.status(400).json({error:'Invalid service account JSON or settings: '+e.message})}});
app.post('/api/google/test',requireRole('ADMIN','OWNER'),async(req,res)=>{try{const {sheets,spreadsheetId,sheetNames}=sheetsClient(); const required=[sheetNames.campers,sheetNames.logs]; const tabs=await validateSheetTabs(sheets,spreadsheetId,required); await verifyEditAccess(sheets,spreadsheetId,sheetNames.logs); event('google_test','ok','Google Sheets connection test succeeded'); res.json({ok:true,message:'Google Sheets connection successful; required tabs exist and edit access verified',tabs,requiredTabs:required,status:googleStatus()})}catch(e){event('google_test','error',e.message); res.status(400).json({error:e.message,status:googleStatus()})}});
app.post('/api/google/import/campers',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await importCampers())}catch(e){event('import_campers','error',e.message); res.status(400).json({error:e.message})}});
app.post('/api/google/sync-pending',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await syncPending())}catch(e){event('sync','error',e.message); db.prepare("UPDATE transactions SET sync_status='error',error=? WHERE sync_status!='synced'").run(e.message); res.status(400).json({error:e.message})}});
app.post('/api/import',requireRole('ADMIN','OWNER'),async(req,res)=>{try{const campers=await importCampers(); res.json({ok:true,campers})}catch(e){event('import','error',e.message); res.status(400).json({error:e.message})}});
app.post('/api/sync',requireRole('ADMIN','OWNER'),async(req,res)=>{try{res.json(await syncPending())}catch(e){event('sync','error',e.message); db.prepare("UPDATE transactions SET sync_status='error',error=? WHERE sync_status!='synced'").run(e.message); res.status(400).json({error:e.message})}});
app.get('/api/status',requireRole('ADMIN','OWNER'),async(req,res)=>{let gs=googleStatus(); const today=new Date().toISOString().slice(0,10); res.json({database:{path:DB_PATH,ok:true},stats:{campers:db.prepare('SELECT count(*) c FROM campers WHERE active=1').get().c,items:db.prepare('SELECT count(*) c FROM items WHERE active=1').get().c,itemsByCategory:db.prepare('SELECT category,count(*) c FROM items WHERE active=1 GROUP BY category ORDER BY category').all(),salesToday:db.prepare("SELECT count(*) c FROM transactions WHERE substr(created_at,1,10)=?").get(today).c,revenueToday:db.prepare("SELECT coalesce(sum(total_cents),0) c FROM transactions WHERE substr(created_at,1,10)=?").get(today).c},googleStatus:gs.configured?'configured':'not configured',google:gs,lastImport:gs.lastImport,lastSync:gs.lastSync,pending:gs.pending,version:APP_VERSION,events:db.prepare('SELECT * FROM sync_events ORDER BY id DESC LIMIT 30').all()})});
app.get('/api/users',requireRole('OWNER'),(req,res)=>res.json(db.prepare('SELECT id,username,display_name,role,active,created_at,updated_at FROM users ORDER BY username').all()));
app.post('/api/users',requireRole('OWNER'),(req,res)=>{const {username,password,displayName,role}=req.body||{}; if(!username||!password||!ROLES[role]) return res.status(400).json({error:'username, password, and role are required'}); const stamp=now(); db.prepare('INSERT INTO users(id,username,display_name,role,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('user_'+nanoid(),username,displayName||username,role,hashPassword(password),1,stamp,stamp); res.json({ok:true})});
app.post('/api/users/:id/password',requireRole('OWNER'),(req,res)=>{if(!req.body?.password) return res.status(400).json({error:'password is required'}); db.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').run(hashPassword(req.body.password),now(),req.params.id); res.json({ok:true})});
if (require.main === module) app.listen(process.env.PORT||3077,()=>console.log(`Camp Store POS running on ${process.env.PORT||3077}`));
module.exports = { app, db, hashPassword, migrate, seedDefaultOwner, initialSeedResult: INITIAL_SEED_RESULT };
